//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2023 Red Hat, Inc. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha08

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"knative.dev/pkg/apis"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSpec) DeepCopyInto(out *ConfigurationSpec) {
	*out = *in
	out.Value = in.Value
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSpec.
func (in *ConfigurationSpec) DeepCopy() *ConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessBuild) DeepCopyInto(out *KogitoServerlessBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessBuild.
func (in *KogitoServerlessBuild) DeepCopy() *KogitoServerlessBuild {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KogitoServerlessBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessBuildList) DeepCopyInto(out *KogitoServerlessBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KogitoServerlessBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessBuildList.
func (in *KogitoServerlessBuildList) DeepCopy() *KogitoServerlessBuildList {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KogitoServerlessBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessBuildSpec) DeepCopyInto(out *KogitoServerlessBuildSpec) {
	*out = *in
	if in.ContainerFile != nil {
		in, out := &in.ContainerFile, &out.ContainerFile
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessBuildSpec.
func (in *KogitoServerlessBuildSpec) DeepCopy() *KogitoServerlessBuildSpec {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessBuildStatus) DeepCopyInto(out *KogitoServerlessBuildStatus) {
	*out = *in
	in.Builder.DeepCopyInto(&out.Builder)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessBuildStatus.
func (in *KogitoServerlessBuildStatus) DeepCopy() *KogitoServerlessBuildStatus {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessPlatform) DeepCopyInto(out *KogitoServerlessPlatform) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessPlatform.
func (in *KogitoServerlessPlatform) DeepCopy() *KogitoServerlessPlatform {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KogitoServerlessPlatform) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessPlatformList) DeepCopyInto(out *KogitoServerlessPlatformList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KogitoServerlessPlatform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessPlatformList.
func (in *KogitoServerlessPlatformList) DeepCopy() *KogitoServerlessPlatformList {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessPlatformList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KogitoServerlessPlatformList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessPlatformSpec) DeepCopyInto(out *KogitoServerlessPlatformSpec) {
	*out = *in
	in.Build.DeepCopyInto(&out.Build)
	in.BuildPlatform.DeepCopyInto(&out.BuildPlatform)
	out.Configuration = in.Configuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessPlatformSpec.
func (in *KogitoServerlessPlatformSpec) DeepCopy() *KogitoServerlessPlatformSpec {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessPlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessPlatformStatus) DeepCopyInto(out *KogitoServerlessPlatformStatus) {
	*out = *in
	in.KogitoServerlessPlatformSpec.DeepCopyInto(&out.KogitoServerlessPlatformSpec)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PlatformCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Info != nil {
		in, out := &in.Info, &out.Info
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessPlatformStatus.
func (in *KogitoServerlessPlatformStatus) DeepCopy() *KogitoServerlessPlatformStatus {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessPlatformStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessWorkflow) DeepCopyInto(out *KogitoServerlessWorkflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessWorkflow.
func (in *KogitoServerlessWorkflow) DeepCopy() *KogitoServerlessWorkflow {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KogitoServerlessWorkflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessWorkflowList) DeepCopyInto(out *KogitoServerlessWorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KogitoServerlessWorkflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessWorkflowList.
func (in *KogitoServerlessWorkflowList) DeepCopy() *KogitoServerlessWorkflowList {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessWorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KogitoServerlessWorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessWorkflowSpec) DeepCopyInto(out *KogitoServerlessWorkflowSpec) {
	*out = *in
	in.Flow.DeepCopyInto(&out.Flow)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessWorkflowSpec.
func (in *KogitoServerlessWorkflowSpec) DeepCopy() *KogitoServerlessWorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessWorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KogitoServerlessWorkflowStatus) DeepCopyInto(out *KogitoServerlessWorkflowStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.Address.DeepCopyInto(&out.Address)
	in.Applied.DeepCopyInto(&out.Applied)
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(apis.URL)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KogitoServerlessWorkflowStatus.
func (in *KogitoServerlessWorkflowStatus) DeepCopy() *KogitoServerlessWorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(KogitoServerlessWorkflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformCondition) DeepCopyInto(out *PlatformCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformCondition.
func (in *PlatformCondition) DeepCopy() *PlatformCondition {
	if in == nil {
		return nil
	}
	out := new(PlatformCondition)
	in.DeepCopyInto(out)
	return out
}
