---
openapi: 3.1.0
info:
  title: Test YAML OpenAPI
  version: 1.0.0
paths:
  /testYamlFunc:
    get:
      operationId: testGetYamlFunc
      responses:
        200:
          content:
            text/plain:
              schema:
                type: object
          description: ""
    put:
      operationId: testPutYamlFunc
      responses:
        200:
          content:
            text/plain:
              schema:
                type: object
          description: ""
