name: "Setup Kogito Tooling Bot on Git"
description: ""

runs:
  using: "composite"
  steps:
    - name: "Setup kogito-tooling-bot"
      shell: bash
      run: |
        echo "STEP: Setup kogito-tooling-bot"
        git config --global user.email "kietooling@gmail.com"
        git config --global user.name "Kogito Tooling Bot (kiegroup)"
