import { Meta } from "@kie-tools/xml-parser-ts";

export const root = {
  element: "DMN14.xsd__definitions",
  type: "DMN14__tDefinitions",
};

export const ns = new Map<string, string>([
  ["https://www.omg.org/spec/DMN/20211108/MODEL/", ""],
  ["", "https://www.omg.org/spec/DMN/20211108/MODEL/"],
  ["https://www.omg.org/spec/DMN/20191111/DMNDI/", "dmndi:"],
  ["dmndi:", "https://www.omg.org/spec/DMN/20191111/DMNDI/"],
  ["http://www.omg.org/spec/DMN/20180521/DC/", "dc:"],
  ["dc:", "http://www.omg.org/spec/DMN/20180521/DC/"],
  ["http://www.omg.org/spec/DMN/20180521/DI/", "di:"],
  ["di:", "http://www.omg.org/spec/DMN/20180521/DI/"],
]);

export const meta: Meta = {
  DMN14__tDMNElement: {
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tNamedElement: {
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tDMNElementReference: {
    "@_href": { type: "string", isArray: false, isOptional: false },
  },
  DMN14__tDefinitions: {
    "@_expressionLanguage": { type: "string", isArray: false, isOptional: true },
    "@_typeLanguage": { type: "string", isArray: false, isOptional: true },
    "@_namespace": { type: "string", isArray: false, isOptional: false },
    "@_exporter": { type: "string", isArray: false, isOptional: true },
    "@_exporterVersion": { type: "string", isArray: false, isOptional: true },
    import: { type: "DMN14__tImport", isArray: true, isOptional: true },
    itemDefinition: { type: "DMN14__tItemDefinition", isArray: true, isOptional: true },
    decision: { type: "DMN14__tDecision", isArray: true, isOptional: true },
    businessKnowledgeModel: { type: "DMN14__tBusinessKnowledgeModel", isArray: true, isOptional: true },
    decisionService: { type: "DMN14__tDecisionService", isArray: true, isOptional: true },
    inputData: { type: "DMN14__tInputData", isArray: true, isOptional: true },
    knowledgeSource: { type: "DMN14__tKnowledgeSource", isArray: true, isOptional: true },
    group: { type: "DMN14__tGroup", isArray: true, isOptional: true },
    textAnnotation: { type: "DMN14__tTextAnnotation", isArray: true, isOptional: true },
    association: { type: "DMN14__tAssociation", isArray: true, isOptional: true },
    elementCollection: { type: "DMN14__tElementCollection", isArray: true, isOptional: true },
    performanceIndicator: { type: "DMN14__tPerformanceIndicator", isArray: true, isOptional: true },
    organizationUnit: { type: "DMN14__tOrganizationUnit", isArray: true, isOptional: true },
    "dmndi:DMNDI": { type: "DMNDI13__DMNDI", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tImport: {
    "@_namespace": { type: "string", isArray: false, isOptional: false },
    "@_locationURI": { type: "string", isArray: false, isOptional: true },
    "@_importType": { type: "string", isArray: false, isOptional: false },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tElementCollection: {
    drgElement: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tDRGElement: {
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tDecision: {
    question: { type: "string", isArray: false, isOptional: true },
    allowedAnswers: { type: "string", isArray: false, isOptional: true },
    variable: { type: "DMN14__tInformationItem", isArray: false, isOptional: true },
    informationRequirement: { type: "DMN14__tInformationRequirement", isArray: true, isOptional: true },
    knowledgeRequirement: { type: "DMN14__tKnowledgeRequirement", isArray: true, isOptional: true },
    authorityRequirement: { type: "DMN14__tAuthorityRequirement", isArray: true, isOptional: true },
    supportedObjective: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    impactedPerformanceIndicator: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    decisionMaker: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    decisionOwner: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    usingProcess: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    usingTask: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    literalExpression: { type: "DMN14__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN14__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN14__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN14__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN14__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN14__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN14__tList", isArray: false, isOptional: true },
    for: { type: "DMN14__tFor", isArray: false, isOptional: true },
    every: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    some: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    conditional: { type: "DMN14__tConditional", isArray: false, isOptional: true },
    filter: { type: "DMN14__tFilter", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tBusinessContextElement: {
    "@_URI": { type: "string", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tPerformanceIndicator: {
    impactingDecision: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    "@_URI": { type: "string", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tOrganizationUnit: {
    decisionMade: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    decisionOwned: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    "@_URI": { type: "string", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tInvocable: {
    variable: { type: "DMN14__tInformationItem", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tBusinessKnowledgeModel: {
    encapsulatedLogic: { type: "DMN14__tFunctionDefinition", isArray: false, isOptional: true },
    knowledgeRequirement: { type: "DMN14__tKnowledgeRequirement", isArray: true, isOptional: true },
    authorityRequirement: { type: "DMN14__tAuthorityRequirement", isArray: true, isOptional: true },
    variable: { type: "DMN14__tInformationItem", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tInputData: {
    variable: { type: "DMN14__tInformationItem", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tKnowledgeSource: {
    "@_locationURI": { type: "string", isArray: false, isOptional: true },
    authorityRequirement: { type: "DMN14__tAuthorityRequirement", isArray: true, isOptional: true },
    type: { type: "string", isArray: false, isOptional: true },
    owner: { type: "DMN14__tDMNElementReference", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tInformationRequirement: {
    requiredDecision: { type: "DMN14__tDMNElementReference", isArray: false, isOptional: true },
    requiredInput: { type: "DMN14__tDMNElementReference", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tKnowledgeRequirement: {
    requiredKnowledge: { type: "DMN14__tDMNElementReference", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tAuthorityRequirement: {
    requiredDecision: { type: "DMN14__tDMNElementReference", isArray: false, isOptional: true },
    requiredInput: { type: "DMN14__tDMNElementReference", isArray: false, isOptional: true },
    requiredAuthority: { type: "DMN14__tDMNElementReference", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tExpression: {
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tItemDefinition: {
    "@_typeLanguage": { type: "string", isArray: false, isOptional: true },
    "@_isCollection": { type: "boolean", isArray: false, isOptional: true },
    itemComponent: { type: "DMN14__tItemDefinition", isArray: true, isOptional: true },
    functionItem: { type: "DMN14__tFunctionItem", isArray: false, isOptional: true },
    typeRef: { type: "string", isArray: false, isOptional: true },
    allowedValues: { type: "DMN14__tUnaryTests", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tFunctionItem: {
    "@_outputTypeRef": { type: "string", isArray: false, isOptional: true },
    parameters: { type: "DMN14__tInformationItem", isArray: true, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tLiteralExpression: {
    "@_expressionLanguage": { type: "string", isArray: false, isOptional: true },
    text: { type: "string", isArray: false, isOptional: true },
    importedValues: { type: "DMN14__tImportedValues", isArray: false, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tInvocation: {
    literalExpression: { type: "DMN14__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN14__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN14__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN14__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN14__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN14__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN14__tList", isArray: false, isOptional: true },
    for: { type: "DMN14__tFor", isArray: false, isOptional: true },
    every: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    some: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    conditional: { type: "DMN14__tConditional", isArray: false, isOptional: true },
    filter: { type: "DMN14__tFilter", isArray: false, isOptional: true },
    binding: { type: "DMN14__tBinding", isArray: true, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tBinding: {
    parameter: { type: "DMN14__tInformationItem", isArray: false, isOptional: false },
    literalExpression: { type: "DMN14__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN14__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN14__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN14__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN14__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN14__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN14__tList", isArray: false, isOptional: true },
    for: { type: "DMN14__tFor", isArray: false, isOptional: true },
    every: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    some: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    conditional: { type: "DMN14__tConditional", isArray: false, isOptional: true },
    filter: { type: "DMN14__tFilter", isArray: false, isOptional: true },
  },
  DMN14__tInformationItem: {
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tDecisionTable: {
    "@_hitPolicy": { type: "DMN14__tHitPolicy", isArray: false, isOptional: true },
    "@_aggregation": { type: "DMN14__tBuiltinAggregator", isArray: false, isOptional: true },
    "@_preferredOrientation": { type: "DMN14__tDecisionTableOrientation", isArray: false, isOptional: true },
    "@_outputLabel": { type: "string", isArray: false, isOptional: true },
    input: { type: "DMN14__tInputClause", isArray: true, isOptional: true },
    output: { type: "DMN14__tOutputClause", isArray: true, isOptional: false },
    annotation: { type: "DMN14__tRuleAnnotationClause", isArray: true, isOptional: true },
    rule: { type: "DMN14__tDecisionRule", isArray: true, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tInputClause: {
    inputExpression: { type: "DMN14__tLiteralExpression", isArray: false, isOptional: false },
    inputValues: { type: "DMN14__tUnaryTests", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tOutputClause: {
    "@_name": { type: "string", isArray: false, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    outputValues: { type: "DMN14__tUnaryTests", isArray: false, isOptional: true },
    defaultOutputEntry: { type: "DMN14__tLiteralExpression", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tRuleAnnotationClause: {
    "@_name": { type: "string", isArray: false, isOptional: true },
  },
  DMN14__tDecisionRule: {
    inputEntry: { type: "DMN14__tUnaryTests", isArray: true, isOptional: true },
    outputEntry: { type: "DMN14__tLiteralExpression", isArray: true, isOptional: false },
    annotationEntry: { type: "DMN14__tRuleAnnotation", isArray: true, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tRuleAnnotation: {
    text: { type: "string", isArray: false, isOptional: true },
  },
  DMN14__tImportedValues: {
    "@_expressionLanguage": { type: "string", isArray: false, isOptional: true },
    importedElement: { type: "string", isArray: false, isOptional: false },
    "@_namespace": { type: "string", isArray: false, isOptional: false },
    "@_locationURI": { type: "string", isArray: false, isOptional: true },
    "@_importType": { type: "string", isArray: false, isOptional: false },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tArtifact: {
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tGroup: {
    "@_name": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tTextAnnotation: {
    "@_textFormat": { type: "string", isArray: false, isOptional: true },
    text: { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tAssociation: {
    "@_associationDirection": { type: "DMN14__tAssociationDirection", isArray: false, isOptional: true },
    sourceRef: { type: "DMN14__tDMNElementReference", isArray: false, isOptional: false },
    targetRef: { type: "DMN14__tDMNElementReference", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tContext: {
    contextEntry: { type: "DMN14__tContextEntry", isArray: true, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tContextEntry: {
    variable: { type: "DMN14__tInformationItem", isArray: false, isOptional: true },
    literalExpression: { type: "DMN14__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN14__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN14__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN14__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN14__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN14__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN14__tList", isArray: false, isOptional: true },
    for: { type: "DMN14__tFor", isArray: false, isOptional: true },
    every: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    some: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    conditional: { type: "DMN14__tConditional", isArray: false, isOptional: true },
    filter: { type: "DMN14__tFilter", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tFunctionDefinition: {
    "@_kind": { type: "DMN14__tFunctionKind", isArray: false, isOptional: true },
    formalParameter: { type: "DMN14__tInformationItem", isArray: true, isOptional: true },
    literalExpression: { type: "DMN14__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN14__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN14__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN14__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN14__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN14__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN14__tList", isArray: false, isOptional: true },
    for: { type: "DMN14__tFor", isArray: false, isOptional: true },
    every: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    some: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    conditional: { type: "DMN14__tConditional", isArray: false, isOptional: true },
    filter: { type: "DMN14__tFilter", isArray: false, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tRelation: {
    column: { type: "DMN14__tInformationItem", isArray: true, isOptional: true },
    row: { type: "DMN14__tList", isArray: true, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tList: {
    literalExpression: { type: "DMN14__tLiteralExpression", isArray: true, isOptional: true },
    invocation: { type: "DMN14__tInvocation", isArray: true, isOptional: true },
    decisionTable: { type: "DMN14__tDecisionTable", isArray: true, isOptional: true },
    context: { type: "DMN14__tContext", isArray: true, isOptional: true },
    functionDefinition: { type: "DMN14__tFunctionDefinition", isArray: true, isOptional: true },
    relation: { type: "DMN14__tRelation", isArray: true, isOptional: true },
    list: { type: "DMN14__tList", isArray: true, isOptional: true },
    for: { type: "DMN14__tFor", isArray: true, isOptional: true },
    every: { type: "DMN14__tQuantified", isArray: true, isOptional: true },
    some: { type: "DMN14__tQuantified", isArray: true, isOptional: true },
    conditional: { type: "DMN14__tConditional", isArray: true, isOptional: true },
    filter: { type: "DMN14__tFilter", isArray: true, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tUnaryTests: {
    "@_expressionLanguage": { type: "string", isArray: false, isOptional: true },
    text: { type: "string", isArray: false, isOptional: false },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tDecisionService: {
    outputDecision: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    encapsulatedDecision: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    inputDecision: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    inputData: { type: "DMN14__tDMNElementReference", isArray: true, isOptional: true },
    variable: { type: "DMN14__tInformationItem", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tChildExpression: {
    "@_id": { type: "string", isArray: false, isOptional: true },
    literalExpression: { type: "DMN14__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN14__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN14__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN14__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN14__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN14__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN14__tList", isArray: false, isOptional: true },
    for: { type: "DMN14__tFor", isArray: false, isOptional: true },
    every: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    some: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    conditional: { type: "DMN14__tConditional", isArray: false, isOptional: true },
    filter: { type: "DMN14__tFilter", isArray: false, isOptional: true },
  },
  DMN14__tTypedChildExpression: {
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    literalExpression: { type: "DMN14__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN14__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN14__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN14__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN14__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN14__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN14__tList", isArray: false, isOptional: true },
    for: { type: "DMN14__tFor", isArray: false, isOptional: true },
    every: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    some: { type: "DMN14__tQuantified", isArray: false, isOptional: true },
    conditional: { type: "DMN14__tConditional", isArray: false, isOptional: true },
    filter: { type: "DMN14__tFilter", isArray: false, isOptional: true },
  },
  DMN14__tIterator: {
    "@_iteratorVariable": { type: "string", isArray: false, isOptional: true },
    in: { type: "DMN14__tTypedChildExpression", isArray: false, isOptional: false },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tFor: {
    return: { type: "DMN14__tChildExpression", isArray: false, isOptional: false },
    "@_iteratorVariable": { type: "string", isArray: false, isOptional: true },
    in: { type: "DMN14__tTypedChildExpression", isArray: false, isOptional: false },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tQuantified: {
    satisfies: { type: "DMN14__tChildExpression", isArray: false, isOptional: false },
    "@_iteratorVariable": { type: "string", isArray: false, isOptional: true },
    in: { type: "DMN14__tTypedChildExpression", isArray: false, isOptional: false },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tConditional: {
    if: { type: "DMN14__tChildExpression", isArray: false, isOptional: false },
    then: { type: "DMN14__tChildExpression", isArray: false, isOptional: false },
    else: { type: "DMN14__tChildExpression", isArray: false, isOptional: false },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN14__tFilter: {
    in: { type: "DMN14__tChildExpression", isArray: false, isOptional: false },
    match: { type: "DMN14__tChildExpression", isArray: false, isOptional: false },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMNDI13__DMNDI: {
    "dmndi:DMNDiagram": { type: "DMNDI13__DMNDiagram", isArray: true, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: true, isOptional: true },
  },
  DMNDI13__DMNDiagram: {
    "dmndi:Size": { type: "DC__Dimension", isArray: false, isOptional: true },
    "dmndi:DMNShape": { type: "DMNDI13__DMNShape", isArray: true, isOptional: true },
    "dmndi:DMNEdge": { type: "DMNDI13__DMNEdge", isArray: true, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: true },
    "@_documentation": { type: "string", isArray: false, isOptional: true },
    "@_resolution": { type: "float", isArray: false, isOptional: true },
    "@_sharedStyle": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: false, isOptional: true },
  },
  DMNDI13__DMNShape: {
    "@_dmnElementRef": { type: "string", isArray: false, isOptional: false },
    "@_isListedInputData": { type: "boolean", isArray: false, isOptional: true },
    "@_isCollapsed": { type: "boolean", isArray: false, isOptional: true },
    "dmndi:DMNLabel": { type: "DMNDI13__DMNLabel", isArray: false, isOptional: true },
    "dmndi:DMNDecisionServiceDividerLine": {
      type: "DMNDI13__DMNDecisionServiceDividerLine",
      isArray: false,
      isOptional: true,
    },
    "dc:Bounds": { type: "DC__Bounds", isArray: false, isOptional: true },
    "@_sharedStyle": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: false, isOptional: true },
  },
  DMNDI13__DMNDecisionServiceDividerLine: {
    "di:waypoint": { type: "DC__Point", isArray: true, isOptional: true },
    "@_sharedStyle": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: false, isOptional: true },
  },
  DMNDI13__DMNEdge: {
    "@_dmnElementRef": { type: "string", isArray: false, isOptional: false },
    "@_sourceElement": { type: "string", isArray: false, isOptional: true },
    "@_targetElement": { type: "string", isArray: false, isOptional: true },
    "dmndi:DMNLabel": { type: "DMNDI13__DMNLabel", isArray: false, isOptional: true },
    "di:waypoint": { type: "DC__Point", isArray: true, isOptional: true },
    "@_sharedStyle": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: false, isOptional: true },
  },
  DMNDI13__DMNLabel: {
    "dmndi:Text": { type: "string", isArray: false, isOptional: true },
    "dc:Bounds": { type: "DC__Bounds", isArray: false, isOptional: true },
    "@_sharedStyle": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: false, isOptional: true },
  },
  DMNDI13__DMNStyle: {
    "@_fontFamily": { type: "string", isArray: false, isOptional: true },
    "@_fontSize": { type: "float", isArray: false, isOptional: true },
    "@_fontItalic": { type: "boolean", isArray: false, isOptional: true },
    "@_fontBold": { type: "boolean", isArray: false, isOptional: true },
    "@_fontUnderline": { type: "boolean", isArray: false, isOptional: true },
    "@_fontStrikeThrough": { type: "boolean", isArray: false, isOptional: true },
    "@_labelHorizontalAlignement": { type: "DC__AlignmentKind", isArray: false, isOptional: true },
    "@_labelVerticalAlignment": { type: "DC__AlignmentKind", isArray: false, isOptional: true },
    "dmndi:FillColor": { type: "DC__Color", isArray: false, isOptional: true },
    "dmndi:StrokeColor": { type: "DC__Color", isArray: false, isOptional: true },
    "dmndi:FontColor": { type: "DC__Color", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
  },
  DC__Color: {
    "@_red": { type: "integer", isArray: false, isOptional: false },
    "@_green": { type: "integer", isArray: false, isOptional: false },
    "@_blue": { type: "integer", isArray: false, isOptional: false },
  },
  DC__Point: {
    "@_x": { type: "float", isArray: false, isOptional: false },
    "@_y": { type: "float", isArray: false, isOptional: false },
  },
  DC__Dimension: {
    "@_width": { type: "float", isArray: false, isOptional: false },
    "@_height": { type: "float", isArray: false, isOptional: false },
  },
  DC__Bounds: {
    "@_x": { type: "float", isArray: false, isOptional: false },
    "@_y": { type: "float", isArray: false, isOptional: false },
    "@_width": { type: "float", isArray: false, isOptional: false },
    "@_height": { type: "float", isArray: false, isOptional: false },
  },
};
