/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.completion;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

/**
 * Parses {@value WorkspaceScan#CONFIG_FILE_NAME}, the file that declares how a
 * workspace's DRL files are grouped.
 *
 * <p>A config file may declare groups directly:
 * <pre>
 * {
 *   "kbases": [
 *     { "name": "validation",
 *       "packages": ["!com.example.validation.internal.*", "com.example.validation.*"],
 *       "includes": ["shared"] },
 *     { "name": "legacy",
 *       "files": ["rules/Types.drl", "rules/Enums.drl"] }
 *   ]
 * }
 * </pre>
 *
 * <p>{@code packages} and {@code includes} carry their {@code kmodule.xml}
 * meaning. {@code files} lists paths explicitly, in order, resolved against the
 * config file's own directory — for groupings that no package pattern can
 * express.
 *
 * <p>It may also adopt a manifest the project already has, without editing it:
 * <pre>
 * {
 *   "sources": [
 *     { "include": "&#42;&#42;/&#42;_Rule-Configs.json",
 *       "pathsRelativeTo": ["&#42;&#42;/src/main/resources"],
 *       "aliases": {
 *         "kbases": "rule.config.list",
 *         "name":   "rule.config.type",
 *         "files":  ["relative.path.list", "absolute.path.list"]
 *       } }
 *   ]
 * }
 * </pre>
 *
 * <p>{@code aliases} maps each canonical key to the key(s) the existing files
 * use; a canonical key with no alias keeps its own name. Mapping several source
 * keys onto one canonical key concatenates their values, which is how a format
 * that splits relative from absolute paths collapses onto a single ordered
 * {@code files} list. Rule manifests are commonly generated by in-house tooling
 * and consumed by in-house code, so requiring them to be rewritten before the
 * editor can read them would put adoption behind a migration.
 */
final class KBaseConfigFile {

    private static final Logger logger = Logger.getLogger(KBaseConfigFile.class.getName());

    private static final String KEY_KBASES = "kbases";
    private static final String KEY_NAME = "name";
    private static final String KEY_PACKAGES = "packages";
    private static final String KEY_INCLUDES = "includes";
    private static final String KEY_FILES = "files";

    private KBaseConfigFile() {
    }

    /**
     * The canonical key names remapped onto whatever an adopted manifest calls
     * them. Each canonical key maps to one or more source keys, tried in order;
     * for {@code files}, the values of every listed key are concatenated.
     */
    record Aliases(Map<String, List<String>> byCanonicalKey) {

        static final Aliases IDENTITY = new Aliases(Map.of());

        List<String> keysFor(String canonicalKey) {
            return byCanonicalKey.getOrDefault(canonicalKey, List.of(canonicalKey));
        }
    }

    /** One adopted manifest format: which files, where their paths root, and the key mapping. */
    record SourceSpec(String includeGlob, List<String> pathsRelativeTo, Aliases aliases) {
    }

    /** Everything one config file contributes. */
    record Parsed(List<KieBaseDecl> declarations, List<SourceSpec> sources) {

        static Parsed empty() {
            return new Parsed(List.of(), List.of());
        }
    }

    /**
     * Reads a config file. A malformed file yields nothing and is logged — one
     * bad config must not take the workspace's other groupings down with it.
     */
    static Parsed parse(Path configFile) {
        try {
            JsonObject root = JsonParser.parseString(Files.readString(configFile)).getAsJsonObject();
            Path base = configFile.getParent();
            return new Parsed(
                    readDeclarations(root, Aliases.IDENTITY, base, configFile),
                    readSources(root));
        } catch (Exception e) {
            logger.log(Level.WARNING, "Could not read DRL grouping config, skipping: " + configFile, e);
            return Parsed.empty();
        }
    }

    /**
     * Reads the same content from the editor's settings rather than a file, so a
     * workspace can be grouped without committing anything to disk. Relative
     * {@code files} entries resolve against {@code workspaceRoot}, there being no
     * config file to anchor them to.
     *
     * <p>Returns nothing for {@code null} or malformed input — a half-typed
     * setting is normal while the user is editing it, and must not take the
     * workspace's other groupings down.
     */
    static Parsed parseInline(String json, Path workspaceRoot) {
        if (json == null || json.isBlank()) {
            return Parsed.empty();
        }
        try {
            JsonObject root = JsonParser.parseString(json).getAsJsonObject();
            return new Parsed(
                    readDeclarations(root, Aliases.IDENTITY, workspaceRoot, null),
                    readSources(root));
        } catch (Exception e) {
            logger.warning("Ignoring malformed DRL grouping settings: " + e.getMessage());
            return Parsed.empty();
        }
    }

    /**
     * Reads group declarations out of an adopted manifest, applying
     * {@code aliases} and resolving relative paths against {@code pathRoots} —
     * the first root under which the entry actually exists wins.
     */
    static List<KieBaseDecl> parseAdopted(Path manifest, Aliases aliases, List<Path> pathRoots) {
        try {
            JsonObject root = JsonParser.parseString(Files.readString(manifest)).getAsJsonObject();
            List<Path> roots = pathRoots.isEmpty() ? List.of(manifest.getParent()) : pathRoots;
            return readDeclarations(root, aliases, roots, manifest);
        } catch (Exception e) {
            logger.log(Level.WARNING, "Could not read adopted rule manifest, skipping: " + manifest, e);
            return List.of();
        }
    }

    private static List<KieBaseDecl> readDeclarations(JsonObject root, Aliases aliases, Path base,
                                                      Path declaredIn) {
        return readDeclarations(root, aliases, base == null ? List.of() : List.of(base), declaredIn);
    }

    private static List<KieBaseDecl> readDeclarations(JsonObject root, Aliases aliases, List<Path> pathRoots,
                                                      Path declaredIn) {
        JsonArray entries = firstArray(root, aliases.keysFor(KEY_KBASES));
        if (entries == null) {
            return List.of();
        }
        List<KieBaseDecl> declarations = new ArrayList<>();
        for (JsonElement element : entries) {
            if (!element.isJsonObject()) {
                continue;
            }
            JsonObject entry = element.getAsJsonObject();
            String name = firstString(entry, aliases.keysFor(KEY_NAME));
            if (name == null || name.isBlank()) {
                continue;
            }
            List<String> packages = allStrings(entry, aliases.keysFor(KEY_PACKAGES));
            List<String> includes = allStrings(entry, aliases.keysFor(KEY_INCLUDES));
            List<Path> files = resolveAll(allStrings(entry, aliases.keysFor(KEY_FILES)), pathRoots);

            if (packages.isEmpty() && files.isEmpty()) {
                logger.warning("Group '" + name.trim() + "' declares neither packages nor files, skipping");
                continue;
            }
            // A group that named no packages must claim only the files it listed;
            // empty packages means "everything" solely in kmodule's own dialect.
            declarations.add(new KieBaseDecl(name.trim(), packages, includes, files, !packages.isEmpty(),
                    KieBaseDecl.Origin.group(declaredIn)));
        }
        return declarations;
    }

    private static List<SourceSpec> readSources(JsonObject root) {
        JsonArray sources = root.getAsJsonArray("sources");
        if (sources == null) {
            return List.of();
        }
        List<SourceSpec> specs = new ArrayList<>();
        for (JsonElement element : sources) {
            if (!element.isJsonObject()) {
                continue;
            }
            JsonObject source = element.getAsJsonObject();
            String include = firstString(source, List.of("include"));
            if (include == null || include.isBlank()) {
                logger.warning("Grouping source without an 'include' glob, skipping");
                continue;
            }
            specs.add(new SourceSpec(
                    include.trim(),
                    allStrings(source, List.of("pathsRelativeTo")),
                    readAliases(source.getAsJsonObject("aliases"))));
        }
        return specs;
    }

    private static Aliases readAliases(JsonObject aliases) {
        if (aliases == null) {
            return Aliases.IDENTITY;
        }
        Map<String, List<String>> byCanonicalKey = new LinkedHashMap<>();
        for (String canonical : List.of(KEY_KBASES, KEY_NAME, KEY_PACKAGES, KEY_INCLUDES, KEY_FILES)) {
            List<String> mapped = stringOrArray(aliases.get(canonical));
            if (!mapped.isEmpty()) {
                byCanonicalKey.put(canonical, mapped);
            }
        }
        return byCanonicalKey.isEmpty() ? Aliases.IDENTITY : new Aliases(Map.copyOf(byCanonicalKey));
    }

    // ── resolution ───────────────────────────────────────────────────────────

    /**
     * Resolves declared path entries. Absolute entries are taken verbatim;
     * relative entries are resolved against the first root under which the file
     * exists, so a workspace with several resource roots needs no per-entry
     * configuration. An entry found under none of them is kept against the first
     * root, which turns a wrong {@code pathsRelativeTo} into a visibly missing
     * file rather than a silently absent group member.
     */
    private static List<Path> resolveAll(List<String> entries, List<Path> pathRoots) {
        List<Path> resolved = new ArrayList<>(entries.size());
        for (String entry : entries) {
            Path candidate = Path.of(entry.replace('\\', '/'));
            if (candidate.isAbsolute()) {
                resolved.add(candidate.toAbsolutePath().normalize());
                continue;
            }
            if (pathRoots.isEmpty()) {
                continue;
            }
            Path fallback = null;
            Path found = null;
            for (Path root : pathRoots) {
                if (root == null) {
                    continue;
                }
                Path absolute = root.resolve(candidate).toAbsolutePath().normalize();
                if (fallback == null) {
                    fallback = absolute;
                }
                if (Files.isRegularFile(absolute)) {
                    found = absolute;
                    break;
                }
            }
            if (found != null) {
                resolved.add(found);
            } else if (fallback != null) {
                resolved.add(fallback);
            }
        }
        return resolved;
    }

    // ── JSON helpers, alias-aware ────────────────────────────────────────────

    private static JsonArray firstArray(JsonObject object, List<String> keys) {
        for (String key : keys) {
            JsonElement element = object.get(key);
            if (element != null && element.isJsonArray()) {
                return element.getAsJsonArray();
            }
        }
        return null;
    }

    private static String firstString(JsonObject object, List<String> keys) {
        for (String key : keys) {
            JsonElement element = object.get(key);
            if (element != null && element.isJsonPrimitive()) {
                return element.getAsString();
            }
        }
        return null;
    }

    /** Concatenates the values of every listed key that is present. */
    private static List<String> allStrings(JsonObject object, List<String> keys) {
        List<String> values = new ArrayList<>();
        for (String key : keys) {
            for (String value : stringOrArray(object.get(key))) {
                if (!values.contains(value)) {
                    values.add(value);
                }
            }
        }
        return values;
    }

    /** Accepts either a bare string or an array of strings. */
    private static List<String> stringOrArray(JsonElement element) {
        if (element == null || element.isJsonNull()) {
            return List.of();
        }
        if (element.isJsonPrimitive()) {
            String value = element.getAsString().trim();
            return value.isEmpty() ? List.of() : List.of(value);
        }
        if (!element.isJsonArray()) {
            return List.of();
        }
        List<String> values = new ArrayList<>();
        for (JsonElement item : element.getAsJsonArray()) {
            if (item.isJsonPrimitive()) {
                String value = item.getAsString().trim();
                if (!value.isEmpty()) {
                    values.add(value);
                }
            }
        }
        return values;
    }
}
