# KIE Sandbox application
# -- The KIE Sandbox application name
name: kie-sandbox

# -- Env variables for KIE Sandbox deployment
env:
  - name: "KIE_SANDBOX_EXTENDED_SERVICES_URL"
    value: "http://127.0.0.1:21345"
  - name: "KIE_SANDBOX_CORS_PROXY_URL"
    value: "http://127.0.0.1:8081"

# @ignored
replicaCount: 1

# -- Image source configuration for the KIE Sandbox image
image:
  registry: quay.io
  account: kie-tools
  name: kie-sandbox-image
  tag: "latest"
  pullPolicy: IfNotPresent

# -- Pull secrets used when pulling KIE Sandbox image
imagePullSecrets: []

# -- Overrides charts name
nameOverride: ""
# -- Overrides charts full name
fullnameOverride: ""

# -- KIE Sandbox ServiceAccount configuration (https://kubernetes.io/docs/concepts/security/service-accounts/)
serviceAccount:
  create: true
  annotations: {}
  name: ""

# @ignored
podAnnotations: {}

# @ignored
podSecurityContext: {}

# @ignored
securityContext: {}

# -- KIE Sandbox Service configuration (https://kubernetes.io/docs/concepts/services-networking/service/)
service:
  type: ClusterIP
  port: 8080
  nodePort: ""

# -- KIE Sandbox Ingress configuration (https://kubernetes.io/docs/concepts/services-networking/ingress/)
ingress:
  enabled: false
  className: "{{ .Values.global.kubernetesIngressClass }}"
  annotations: {}
  hosts:
    - host: kie-sandbox.{{ .Values.global.kubernetesClusterDomain }}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# -- KIE Sandbox OpenShift Route configuration (https://docs.openshift.com/container-platform/4.14/networking/routes/route-configuration.html)
openshiftRoute:
  enabled: false
  annotations: {}
  host: kie-sandbox.{{ .Values.global.openshiftRouteDomain }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None

# @ignored
resources: {}

# -- KIE Sandbox HorizontalPodAutoscaler configuration (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# @ignored
nodeSelector: {}

# @ignored
tolerations: []

# @ignored
affinity: {}

# @ignored
global:
  openshiftRouteDomain: ocp-example.com
  kubernetesIngressClass: nginx
  kubernetesClusterDomain: k8s-example.com
