kind: ImageStreamList
apiVersion: v1
metadata:
  name: kogito-image-streams
  annotations:
    description: ImageStream definitions for Kogito images
    openshift.io/provider-display-name: Kie Group.
items:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-runtime-native
      annotations:
        openshift.io/display-name: Runtime image for Kogito based on Quarkus native image
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for Kogito based on Quarkus native image
            iconClass: icon-jbpm
            tags: runtime,kogito,quarkus
            supports: quarkus
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-runtime-native:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-runtime-jvm
      annotations:
        openshift.io/display-name: Runtime image for Kogito based on Quarkus or Springboot JVM image
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for Kogito based on Quarkus or Springboot JVM image
            iconClass: icon-jbpm
            tags: runtime,kogito,quarkus,springboot,jvm
            supports: quarkus
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-runtime-jvm:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-s2i-builder
      annotations:
        openshift.io/display-name: Platform for building Kogito based on Quarkus or Springboot
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Platform for building Kogito based on Quarkus or Springboot
            iconClass: icon-jbpm
            tags: s2i-builder,kogito,quarkus,springboot
            supports: quarkus
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-s2i-builder:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-swf-builder
      annotations:
        openshift.io/display-name: Kogito Serverless Workflow builder with basic Quarkus SWF extensions preinstalled
        openshift.io/provider-display-name: KIE Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Kogito Serverless Workflow builder with minimum Quarkus extensions libraries preinstalled
            iconClass: icon-jbpm
            tags: kogito,quarkus,swf,maven
            supports: quarkus
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-swf-builder:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-base-builder
      annotations:
        openshift.io/display-name: Kogito base builder
        openshift.io/provider-display-name: KIE Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Kogito base builder
            iconClass: icon-jbpm
            tags: kogito,jdk,maven
            supports: quarkus
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-base-builder:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-data-index-infinispan
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Data Index Service for Infinispan persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Data Index Service with Infinispan
            iconClass: icon-jbpm
            tags: kogito,data-index,data-index-infinispan
            supports: persistence backed by Infinispan Server
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-data-index-infinispan:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-data-index-ephemeral
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Data Index Service for ephemeral PostgreSQL persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Data Index Service with ephemeral PostgreSQL
            iconClass: icon-jbpm
            tags: kogito,data-index,data-index-ephemeral
            supports: persistence backed by ephemeral PostgreSQL Server
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-data-index-ephemeral:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-data-index-mongodb
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Data Index Service for MongoDB persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Data Index Service with Mongodb
            iconClass: icon-jbpm
            tags: kogito,data-index,data-index-mongodb
            supports: persistence backed by Mongodb server
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-data-index-mongodb:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-data-index-postgresql
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Data Index Service for PostgreSQL persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Data Index Service with PostgreSQL
            iconClass: icon-jbpm
            tags: kogito,data-index,data-index-postgresql
            supports: persistence backed by PostgreSQL server
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-data-index-postgresql:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-trusty-infinispan
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Trusty Service for Infinispan persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Trusty Service with Infinispan
            iconClass: icon-jbpm
            tags: kogito,trusty,trusty-infinispan
            supports: persistence backed by Infinispan server
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-trusty-infinispan:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-trusty-redis
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Trusty Service for Redis persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Trusty Service with Redis
            iconClass: icon-jbpm
            tags: kogito,trusty,trusty-redis
            supports: persistence backed by Redis server
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-trusty-redis:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-trusty-postgresql
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Trusty Service for PostgreSQL persistence provider
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Trusty Service with PostgreSQL
            iconClass: icon-jbpm
            tags: kogito,trusty,trusty-postgresql
            supports: persistence backed by PostgreSQL RDBMS
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-trusty-postgresql:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-trusty-ui
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Trusty UI Service
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Trusty UI Service
            iconClass: icon-jbpm
            tags: kogito,trusty-ui
            supports: Audit UI
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-trusty-ui:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-jit-runner
      annotations:
        openshift.io/display-name: Runtime image for the Kogito JIT Runner
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito JIT Runner
            iconClass: icon-jbpm
            tags: kogito,jit-runner
            supports: JIT Runner
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-jit-runner:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-explainability
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Explainability Service
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Explainability Service
            iconClass: icon-jbpm
            tags: kogito,explainability
            supports: explainability for decisions
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-explainability:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-jobs-service-ephemeral
      annotations:
        openshift.io/display-name: Runtime image for Kogito in memory Jobs Service
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for Kogito in memory Jobs Service
            iconClass: icon-jbpm
            tags: kogito,jobs-service
            supports: out-of-box process timers
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-jobs-service-ephemeral:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-jobs-service-infinispan
      annotations:
        openshift.io/display-name: Runtime image for Kogito Jobs Service based on Infinispan
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for Kogito Jobs Service based on Infinispan
            iconClass: icon-jbpm
            tags: kogito,jobs-service
            supports: out-of-box process timers
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-jobs-service-infinispan:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-jobs-service-mongodb
      annotations:
        openshift.io/display-name: Runtime image for Kogito Jobs Service based on Mongodb
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for Kogito Jobs Service based on Mongodb
            iconClass: icon-jbpm
            tags: kogito,jobs-service
            supports: out-of-box process timers
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-jobs-service-mongodb:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-jobs-service-postgresql
      annotations:
        openshift.io/display-name: Runtime image for Kogito Jobs Service based on Postgresql
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for Kogito Jobs Service based on Postgresql
            iconClass: icon-jbpm
            tags: kogito,jobs-service
            supports: out-of-box process timers
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-jobs-service-postgresql:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-jobs-service-allinone
      annotations:
        openshift.io/display-name: All in One Runtime image for Kogito Jobs Service
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: All in One Runtime image for Kogito Jobs Service
            iconClass: icon-jbpm
            tags: kogito,jobs-service, all-in-one
            supports: out-of-box process timers
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-jobs-service-allinone:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-management-console
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Management Console
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Management Console
            iconClass: icon-jbpm
            tags: kogito,management-console
            supports: business process management
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-management-console:999-SNAPSHOT
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: kogito-task-console
      annotations:
        openshift.io/display-name: Runtime image for the Kogito Task Console
        openshift.io/provider-display-name: Kie Group.
    spec:
      tags:
        - name: '999-SNAPSHOT'
          annotations:
            description: Runtime image for the Kogito Task Console
            iconClass: icon-jbpm
            tags: kogito,task-console
            supports: business process management
            version: '999-SNAPSHOT'
          referencePolicy:
            type: Local
          from:
            kind: DockerImage
            name: quay.io/kiegroup/kogito-task-console:999-SNAPSHOT
