packages:
  - "packages/*"
  - "examples/*"
  - "scripts/*"
overrides:
  "@apidevtools/json-schema-ref-parser>js-yaml": "^3.14.2"
  "@istanbuljs/load-nyc-config>js-yaml": "^3.14.2"
  "@types/react": "^17.0.6"
  "cross-spawn": "^7.0.6"
  "d3-color": "3.1.0"
  "graphql": "14.3.1"
  "json-refs>js-yaml": "^3.14.2"
  "minimatch@^5>brace-expansion": "^2.0.2"
  "openapi-types": "7.2.3"
  "react-dropzone": "^11.4.2"
  "superagent": "10.2.2"
  "xmlbuilder2>js-yaml": "^3.14.2"
  "@types/node": "24.10.11"
