---
openapi: 3.0.3
info:
  title: test API
  version: 1.0.0-SNAPSHOT
paths:
  /testfunc:
    get:
      operationId: testFuncId
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: json
