UberFire Overview
=================

This document is a survey of the features and capabilities of the
UberFire Rich Client Platform. If you are a software developer who's
new to UberFire and you're wondering what it's all about, then you've
come to the right place. If you're wondering whether UberFire is a fit
for your new (or existing) web application, this is also the right
place to start.

What is UberFire?
-----------------

UberFire is a rich client platform that helps you build web
applications. Both the client-side and server-side code are written in
Java; the server-side code is deployed as a Java EE `.war` file, and
the client-side code is deployed as precompiled JavaScript. No
Java-to-JavaScript translation occurs at runtime.

UberFire itself is built upon a general-purpose web framework called
Errai. Errai's design helps you maximize the amount of code shared
between the client and the server, leans toward a declarative (rather
than procedural) style, and strives to help you take advantage of the
type safety inherent to Java programs. Programs written in UberFire
can use Errai features directly.

Errai, in turn, is built on top of the Google Web Toolkit (GWT), which
provides a subset of the Java SE library, a large standard library of
user interface widgets, and most importantly, a highly optimized
Java-to-JavaScript compiler. There is also a huge collection of
third-party free and proprietary add-on libraries for GWT. UberFire
applications can take advantage of most of these.

The overarching programming model in UberFire is CDI, the standard
Dependency Injection and loosely-coupled eventing API that permeates
Java EE 6 and newer. The CDI programming model is present throughout 

UberFire makes it easy to include any or all of the following elements
in your application:

* User identity (login/logout) and authorization (access roles and permissions)
* A modular, user-configurable user interface (the user can rearrange designated portions of the UI by drag-and-drop)
** The framework can remember an arbitrary number of such arrangements (each is called a Perspective)
    and the user can switch between them
** The framework can limit visibility of UI elements (say, toolbar buttons and menu items)
    based on security authorization
* Nestable drop-down menus
* Tool bars
* Navigation through tree-structured collection of documents (a virtual filesystem or VFS)
** Each file in the VFS supports change tracking, revision control, and update notification
** File types can be associated with custom viewers and editors
** The contents of the VFS can also be searched using a performant full-text search engine
    (TODO: is this correct? I think this is the purpose of uberfire-metadata)
* Application components can be written in Java or JavaScript. Components can interoperate
  regardless of which language they are implemented in.

To be clear, an application built with UberFire does not have to use
all of the features listed above. If your application needs toolbars and a
version-tracking VFS, but not a drag-and-drop layout or nested menus,
UberFire may still be a good choice.


UberFire Core Concepts
~~~~~~~~~~~~~~~~~~~~~~

These concepts are expressed in the core `uberfire-api` module,
footnote:[A few of these concepts actually come from Errai and GWT,
but the distinction isn't important when getting started with
UberFire.] so they permeate all parts of the UberFire framework:

* Workbench
+
Top level container for toolbars, menu bars and perspectives.
* Perspectives
+
Child of the Workbench. Group and layout panels in a composite container.
* Panels
+
Child of a perspective and a container for Parts. Different types of panel can have different behaviours, for example (as provided by default):
** Single (active) part rendered, selection of other parts using tabs. Supports drag and drop repositioning of parts.
** Single (active) part rendered, selection of other parts from a drop-down listbox. Supports drag and drop repositioning of parts.
** Single part; fixed content. Drag and drop support disabled.
* Parts
+
Child of a Panel. A Part is the finest grained logical entity within the Workbench. A Part is represented by a Place and can be a Screen or an Editor.
* Place
+
Everything within the Uberfire framework is considered to be a Place; and can be launched programmatically. All places should have a unique identifier within the Workbench.
* PlaceRequest
+
A request for the Workbench to go to a Place. PlaceRequests can represent a perspective, pop-up, screen or editor.
* Path
+
A Path is a location within any Virtual File System configured within UberFire. Editors can be defined to respond to different Paths.
* Screens
+
A screen is not associated to a Path pattern and can be launched by requesting the corresponding Place. Screens can be used for static content; or for resources beyond UberFire's VFS mechanisms. 
* Editors
+
An editor is associated to a Path pattern. Requests for Places that correspond to a Path will launch corresponding editor. Editors can be used for resources within UberFire's VFS mechanisms.
* Widgets
+
UberFire is not a widget library and can be used with different third party libraries; however some widgets are provided for core Workbench features. 
* Contexts
+
TODO
* Menus
+
items, groups, factories, commands, positions
* Tool bars
+
items, icons, types
* Resources
* File Navigators
* Identity
* Marshalling
* Workbench Events (TODO: why are these defined globally rather than in the uberfire-workbench module?)
** ApplicationReadyEvent
+
Signal when certain resources have been injected into the GWT Host Page and other bootstrap processes complete. Raised by UberFire. 
** BeforeClosePlaceEvent
+
Signal when a Part is about to be closed; normally in response to the user electing to interactively close a Part. Screens and Editors can veto the closure (for example if they contain unsaved content). Raised by Uberfire. 
** ClosePlaceEvent
+
Signal when a Part is closed. This event signals the removal of a Part from a Panel. Raised by Uberfire.
** ContextUpdateEvent
+
TODO
** DropPlaceEvent
+
Part of the drag and drop support. Signals a Part has been dragged to and dropped on a target Panel. Raised by Uberfire. 
** MaximizePlaceEvent
+
Signals a Part has been "maximized" to consume the whole Workbench client region (Note: Work in progress). Raised by Uberfire.
** MinimizePlaceEvent
+
Signals a Part has been "minimized" to a status bar within the Workbench (Note: Work in progress). Raised by Uberfire.
** NewPerspectiveEvent
+
TODO
** NewWorkbenchScreenEvent
+
TODO
** NotificationEvent
+
Signal a informative notification (e.g. "File saved" etc) that appears within the Workbench as a popup message. Raised by whoever needs to inform users of a notication.
** PanelFocusEvent
+
Signal a Panel has received the input focus. Raised by Uberfire.
** PerspectiveChange
+
Signal a change in active Perspective. Raised by Uberfire.
** PlaceGainFocusEvent
+
Signal a Place has gained the input focus. Raised by Uberfire.
** PlaceLostFocusEvent
+
Signal a Place has lost the input focus. Raised by Uberfire.
** SavePlaceEvent
+
Signal an Editor can have it's state saved. Raised by developers using Uberfire from Widgets outside of the Editor itself (e.g. a Workbench Menubar entry). 
** SelectPlaceEvent
+
Signal a Place has been selected. Raised by Uberfire.
** RestorePlaceEvent
+
TODO

* VFS Events (TODO: why are these defined globally rather than in the uberfire-workbench module?)
** ResourceAddedEvent
+
Signal a resource has been added to a VFS. Raised by VFS.
** ResourceBatchChangesEvent
+
Signal a batch change to various resources within a VFS. Raised by VFS.
** ResourceCopiedEvent
+
Signal a resource has been copied within a VFS. Raised by VFS.
** ResourceDeletedEvent
+
Signal a resource has been deleted from a VFS. Raised by VFS.
** ResourceOpenedEvent
+
Signal a resource has been opened (Note: Uberfire does not make raise or observe the event itself) 
** ResourceRenamedEvent
+
Signal a resource has been renamed within a VFS. Raised by VFS.
** ResourceUpdatedEvent
+
Signal a resource has been modified within a VFS. Raised by VFS.

UberFire Backend API Concepts
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

These concepts are expressed in the `uberfire-backend-api` module, which
TODO: characterize this module; it's (mostly) not just for the server-side.

* Deployment
* Organizational Unit
* Repository
* Configuration (server-side only): ConfigGroup, ConfigItem, ConfigurationFactory
* VFS (Virtual Filesystem)


UberFire Client API Concepts
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

These concepts are expressed in the `uberfire-client-api` package,
which defines an API that's only accessible to client-side
(in-browser) code.

* Annotations
** DefaultPosition
+
Marker annotation to allow either `@WorkbenchEditor` 's or `@WorkbenchScreen` 's to declare a method that returns the default location of the component in a perspective when opened by the framework. NOTE: This is specific to the NSEW perspective type. Work is in progress to provide support for additional types of perspective.
** Intercept
+
TODO
** Perspective
+Marker annotation to allow a `@WorkbenchPerspective` to declare a method that returns a PerspectiveDefinition object, defining the workbench perspective.
** SplashBodySize
+
TODO
** SplashFilter
+
TODO
** WorkbenchContext
+
TODO
** WorkbenchContextId
+
TODO
** WorkbenchEditor
+
A marker annotation to declare a class as being a Workbench Editor. Editors relate to specific resources within the framework, defined by their ResourceTypeDefinition.
** WorkbenchMenu
+
A marker annotation to declare a method within a `@WorkbenchPerspective`, `@WorkbenchEditor` or `@WorkbenchScreen` that returns a Menus object defining a menu to be shown by the framework when the perspective, editor or screen is displayed.
** WorkbenchPartTitle
+
A marker annotation to declare a method within a `@WorkbenchEditor` or `@WorkbenchScreen` that returns a String defining the title for the component.
** WorkbenchPartTitleDecoration
+
A marker annotation to declare a method within a `@WorkbenchEditor` or `@WorkbenchScreen` that returns an IsWidget object to be used as a decoration, beside the @WorkbenchPartTitle.
** WorkbenchPartView
+
A marker annotation to declare a method within a `@WorkbenchEditor` or `@WorkbenchScreen` that returns a IsWidget object representing the view (or user-interface) of the component.
** WorkbenchPerspective
+
Marker annotation to declare a class as providing a perspective definition. The definition itself is returned from a method within the `@WorkbenchPerspective` annotated with @Perspective. 
** WorkbenchPopup
+
Marker annotation to declare a class as being a popup that can be displayed by the framework.
** WorkbenchScreen
+
A marker annotation to declare a class as being a Workbench Screen. Screens would usually display static content, or at least content that is not dependent upon a Path within the underlying VFS. The screen could still consume external resources (e.g. query a database) however it does not integrate with the framework's use of Paths.
** WorkbenchSplashScreen
+
TODO
** WorkbenchToolbar
+
A marker annotation to declare a method within a `@WorkbenchPerspective`, `@WorkbenchEditor` or `@WorkbenchScreen` that returns a ToolBar object defining a toolbar to be shown by the framework when the perspective, editor or screen is displayed.

* Interfaces
** UberView
+
A convenience interface to support linking a View to it's Presenter as required by implementations of the MVP pattern. Uberfire itself does not impose use of MVP.

* Events
** ChangeTitleWidgetEvent
+
A CDI event that provides support for `@WorkbenchEditor` 's and @Workbench screens to inform the framework that their title or decoration should be updated.

* Types
** ClientResourceType
+
Extends ResourceTypeDefinition which is a server-side model for a resource type; allowing `@WorkbenchEditor` 's to specify the types of resource they are capable of handling.

UberFire Commons Concepts
~~~~~~~~~~~~~~~~~~~~~~~~~

These concepts are expressed in the `uberfire-commons` package,
which contains a mix of server-only definitions shared client/server definitions.

* Clustering (server-only, see also UberFire I/O)
* Pair, a generic 2-tuple (client + server)
* Lock Service (server-only)
* Cluster Messaging (server-only, for clustered deployments; distinct from Errai Bus messages)
** AsyncCallback, MessageHandler, MessageHandlerResolver, MessageService, MessageType
* CDI Startup Beans (the @Startup annotation) (server-only)
* PortablePreconditions (client + server), a collection of static methods for checking common preconditions (reference not null, list not empty, etc.)
** Note: Errai has a shared class called Assert which serves a similar purpose
* Preconditions (server-only), precondition checks that are not GWT-translatable


UberFire I/O Concepts
~~~~~~~~~~~~~~~~~~~~~

These concepts are expressed in the `uberfire-io` package,
which contains mostly server-only code.

* Dublin Core (TM) metadata
* FileSystemType (client + server)
* Clustering (see also UberFire Commons)
* IO Services (Clustered service, Search Service, Watch Service)


UberFire JS Concepts
~~~~~~~~~~~~~~~~~~~~

These concepts are expressed in the `UberFire-js` package, which
exposes a JavaScript API for some aspects of the UberFire framework.
This gives application developers the option to write UberFire
applications partly or entirely in JavaScript.

* JavaScript native plugin, with types representing
** Entry points
** Perspectives
** Plugins
** Workbench perspective activities
** Workbench screen activities
** Panel definitions
** Part definitions


UberFire Metadata Concepts
~~~~~~~~~~~~~~~~~~~~~~~~~~

These concepts are expressed in the `uberfire-metadata` package,
which appears to be a full-text search and indexing feature (TODO: is this correct?)

The UberFire Metadata module includes an API submodule which defines
the following concepts, and one implementation of the API (a "metadata
backend") that relies on Apache Lucene:

* Metadata index engine
* Metamodel store
* "K" objects:
** KObject
** KObjectKey
** KObjectSimpleKey
** KProperty
** KPropertyBag
* MetaObject
* MetaProperty
* MetaType
* Cluster segment
* Date range
* Search index

There is also a small submodule called `uberfire-metadata-commons-io`
which introduces the following concepts:

* Batch index
* IO Search index


UberFire NIO2 Concepts
~~~~~~~~~~~~~~~~~~~~~~

The `uberfire-nio2-backport` module includes a backport of the Java SE
7 "new new IO" APIs to Java SE 6. The backport is repackaged under the
org.uberfire.java.nio.* namespace. It also provides a couple of utility
classes in the `org.apache.commons.io` package.

The UberFire NIO2 API is only intended for use on the server side.

UberFire includes NIO2 FileSystem implementations for the plain
filesystem, for git repositories (via jgit), and for the Eclipse
virtual filesystem.


UberFire Security Concepts
~~~~~~~~~~~~~~~~~~~~~~~~~~

These concepts are expressed in the `uberfire-security-api` package,
and they are all available to both client- and server-side code.

* Security interceptor annotations (for types and methods)
** `@All`
** `@Authorized`
** `@Deny`
** `@Roles({})`
* Authenticated Storage
* Authentication Manager
* Authentication Provider
* Authentication Result
* Authentication Scheme
* Authentication Source
* Authentication Status
* Credential
* Principal
* Role
* Subject Properties
* Authorization Manager
* Decision Managers:
** Resource Decision Manager
** Role Decision Manager
* Roles Resource
* Runtime Resource
* Voting Strategy
* Crypt Provider
* Identity
* Resource
* Resource Manager
* Security Context
* Security Manager
* Subject

There is an `uberfire-security-client` module, but it's just
"plumbing:" it doesn't expose any concepts that are used directly in
application code.

These concepts are expressed in the `uberfire-security-server`
package, which contains a variety of server-side implementations of
the UberFire Security API types:

* Authentication Managers: HTTP (servlets)
* Authentication Schemes: Form, HttpBasic, JACC, "Remember Me" Cookie
* Authenticated Storage: Cookie Storage, Http Session Storage
* Authentication Providers: Default, "Remember Me" Cookie
* Authentication Sources: Database (JDBC), JACC, users.properties file
* Security Interceptors: Role-based, Trait-based
* Crypt Providers: Default
* Security Contexts: HTTP (servlets)
* Security Managers: HTTP (servlets)
* Voting Strategies: Affirmative, Consensus, Unanimous

Plus some new concepts:

* URL Resource
* Ant Paths


UberFire Server Concepts
~~~~~~~~~~~~~~~~~~~~~~~~

These concepts are expressed in the `uberfire-server` package,
which contains some server-side functionality.

* UberFire Image Servlet
** UberFire Image Paths
* UberFire Servlet
** App template, header template, footer template, user data template


UberFire Widgets Concepts
~~~~~~~~~~~~~~~~~~~~~~~~~

UberFire is not a widget library but does include a number of useful widgets 
for that can be re-used.

UberFire Widgets are packaged into modules:
`uberfire-widgets-commons`, `uberfire-widgets-core-client`, and
`uberfire-widget-markdown`.

The `uberfire-widgets-commons` module introduces the following concepts:

* Animations
** Fade in animation
+
Simple linear animation to fade a Widgets transaparency from 100% to 0%.
** Fade out animation
+
Simple linear animation to fade a Widgets transaparency from 0% to 100%.
** Sequenced Animations
+
An extension of GWT's Animation allowing animations to be sequenced one after another.
** Sequencer
+
A utility class to place numerous SequencedAnimations into a List and run the whole as a single animation.

* Popups
** ErrorPopup
+
A generic popup to show an error message.
** ConcurrentChangePopup
+
A popup allowing the user to take different actions when a concurrent modification to a Path has been detected by the framework.
** ModalFooterOKButton
+
Popup footer showing an "OK" button. Action for button is a Command.
** Busy popup
+
A popup that can be used to show a message when a log running task is being executed.
** ModalFooterOKCancelButtons
+
Popup footer showing "OK" and "Cancel" buttons. Actions for buttons are Commands.
** ModalFooterYesNoCancelButtons
+
Popup footer showing "Yes", "No" and "Cancel" buttons. Actions for buttons are Commands.

* MultiPageEditor
+
UberFire's implementation of a TabBar that allows the tab section to be located in different positions.

** Page
+
A page that can be added to the MultiPageEditor.

* Miscellaneous
+
There are a number of miscellaneous widgets that largely exist in UberFire to demonstrate a "show case" web application.
Furthermore a large number of them exist solely because UberFire eminated from a need to develop a Workbench for
Drools Guvnor 6.0.x. Historically a lot of existing Drools Guvnor widgets were moved into `uberfire-widgets-commons`
however should be considered deprecated.
 
** Lazy stack panel and the LoadContentCommand
** Restricted entry text box
** Clickable label
** Context dropdown button
** Decorated disclosure panel
** Dirtyable: widgets, composites, containers, horizontal panes, vertical panes, and FlexTables
** Editor widget
** Form style layout
** Form style popup
** Pretty form layout
** Image button
** Info cube
** Info popup
** Numeric text boxes (for each Java numeric type from byte to BigDecimal)
** Popups
** Resizable textarea
** Small label
** UberBreadcrumbs
** Common resources: images, alted images, css, general resources
** Simple and paged tables: cells, columns, titled cells; sortable headers, sort direction
** Comparable image resources
** A collection of built-in images (gif & png) for corners, pager buttons, dialog status icons, and more (see also uberfire-widgets-core-client)

The `uberfire-widgets-core-client` module introduces the following concepts:

* Components implemented as MVP:
** DefaultFileEditor
+
A `@WorkbenchEditor` that provides the ability to upload and download any file not explicitly handled by another `@WorkbenchEditor`'s ResourceType.
** TextEditor
+
A `@WorkbenchEditor` that provides the ability to edit text files (*.txt) or "dot" files (file names prefixed with a ".", otherwise known as "Meta data" files) in a TextArea.
** FileExplorer
+
A `@WorkbenchScreen` that provides a simple Tree based explorer of an underlying VFS. Clicking a file launches the corresponding `@WorkbenchEditor`.
The FileExplorer also registers a menu with the UberFire framework that gives users access to the RepositoriesEditor and ability to clone or create new Repositories.
** FileNavigator
+
A `@WorkbenchScreen` that provides more sophisticated navigation of an underlying VFS. 
** MetaFileEditor
+
A `@WorkbenchEditor` that provides the ability to edit "Meta data" files (file names prefixed with a ".") in a TextArea. "Meta data" files are also called "dot" files.
** RepositoriesEditor
+
A `@WorkbenchScreen` that provides the ability to view Repositories configured within the underlying VFS.
** RepositoryEditor
+
A `@WorkbenchScreen` that shows details of a Repository configured within the underlying VFS.
** IFrameScreen
+
A simple `@WorkbenchScreen` that supports showing content from a URL within an IFRAME.
** Wizard framework
+
A simple framework to support the implementation of "Wizard" type dialogs, where content is completed over a series of pages.

The `uberfire-widget-markdown` module introduces the following concepts:

* Markdown
+
An example `@WorkbenchScreen` that demonstrates a "live" editor for the Markdown text formatting syntax (http://en.wikipedia.org/wiki/Markdown).
The editor is sub-divided into two region; one allows entry of text markdown and the other shows a "live" (i.e. updated in real-time) preview of the rendered mark-down.


UberFire Workbench Concepts
~~~~~~~~~~~~~~~~~~~~~~~~~~~

These concepts are expressed in the `uberfire-workbench` package,
which provides annotation processors for the core annotations in
`uberfire-client-api`. 

UberFire supports re-use or authoring of any widgets however promotes use of the MVP (Model, View, Presenter) design 
pattern. Both `@WorkbenchScreen` 's and `@WorkbenchEditor` 's need only declare a minimal number of "hooks" to UberFire. 
Legacy widgets too can be simply wrapped to work within UberFire.  

* The Workbench physical hierarchy (top to bottom): 
** User application
** UberFire Workbench
** UberFire `@WorkbenchPerspective`
** UbefFire `@WorkbenchScreen` or `@WorkbenchEditor`

* The Workbench logical hierachy (top to bottom):
** User application
** Workbench
** Perspective
** Panel
** Part

* The Workbench logical-to-physical mapping (top to bottom):
** Perspective -> `@WorkbenchPerspective`
** Part -> `@WorkbenchScreen` or `@WorkbenchEditor`

* The Workbench relationships:
** Workbench -> [1..n] -> Perspective -> [1..n] -> Panel -> [1..n] -> Part

* Annotation processors for:
** `@WorkbenchPerspective`
** `@WorkbenchContext`
** `@WorkbenchEditor`
** `@WorkbenchScreen`
** `@WorkbenchPopup`
* GWT Bootstrap and UberFireConfigurator
** FontAwesome resources
* Workbench Parts
* The UberFire MVP framework
** Places:
*** Place Requests
*** The Place Request History Mapper
*** Place Status
*** The Place Resolver
*** Place History
** Activities:
*** Activities and the activity lifecycle
*** The activity manager
*** Popup Activities
*** Workbench Activities
*** Workbench Context Activities
*** Workbench Editor Activities
*** Workbench Perspective Activities
*** Workbench Screen Activities
*** The Acvitity Beans Cache
*** The Activity Manager
*** Context Activities
*** Context-sensitive Activities
** Panels and Layouts:
*** The Panel Manager
*** Workbench Panels
*** Multi-part Workbench Panels
*** Multi List Workbench Panels
*** Multi Tab Workbench Panels
*** Simple Workbench Panels
*** Static Workbench Panels
*** Split Panels
*** Multi-part Widgets
*** Panel Helpers (North, South, East, West)
** Accept Items
** Commands
** Paged Tables
* Associated Resources
* The Bean Factory
* Drag and Drop:
** The Compass Widget
** Drag Areas
** The Drag and Drop Manager
** The Drag Context
* The List Bar Widget
* The Workbench Menu Bar
** Part Context Menus
** Perspective Context Menus
* Context Panels
* Requires Resize Flow Panels
* Requires Resize Focus Panels
* Static Focused Resize Panels
* Workbench Toolbars
