---
apiVersion: v1
data:
  camelroute.xml: '<route routeConfigurationId="xmlError">
    <from uri="timer:xml?period=5s"/>
    <log message="I am XML"/>
    <throwException exceptionType="java.lang.Exception" message="Some kind of XML error"/>
    </route>'
  camelroute.yaml: "- from:
    uri: direct:numberToWords
    steps:
    - bean:
    beanType: java.math.BigInteger
    method: valueOf
    - setHeader:
    name: operationName
    constant: NumberToWords
    - toD:
    uri: cxf://{{com.dataaccess.webservicesserver.url}}?serviceClass=com.dataaccess.webservicesserver.NumberConversionSoapType&wsdlURL=/wsdl/numberconversion.wsdl"
metadata:
  name: mycamel-configmap
kind: ConfigMap
---
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: greeting
  annotations:
    sonataflow.org/description: Greeting example on k8s!
    sonataflow.org/version: 0.0.1
    sonataflow.org/profile: dev
spec:
  resources:
    configMaps:
      - configMap:
          name: mycamel-configmap
  flow:
    start: ChooseOnLanguage
    functions:
      - name: greetFunction
        type: custom
        operation: sysout
    states:
      - name: ChooseOnLanguage
        type: switch
        dataConditions:
          - condition: '${ .language == "English" }'
            transition: GreetInEnglish
          - condition: '${ .language == "Spanish" }'
            transition: GreetInSpanish
        defaultCondition: GreetInEnglish
      - name: GreetInEnglish
        type: inject
        data:
          greeting: "Hello from JSON Workflow, "
        transition: GreetPerson
      - name: GreetInSpanish
        type: inject
        data:
          greeting: "Saludos desde JSON Workflow, "
        transition: GreetPerson
      - name: GreetPerson
        type: operation
        actions:
          - name: greetAction
            functionRef:
              refName: greetFunction
              arguments:
                message: ".greeting+.name"
        end: true
