{{- if .Values.sandbox.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kie-sandbox-helm-chart.sandbox.serviceAccountName" . }}
  labels:
    {{- include "kie-sandbox-helm-chart.sandbox.labels" . | nindent 4 }}
  {{- with .Values.sandbox.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
