apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-clustermanger-role
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
      - customresourcedefinitions
      - configmaps
      - deployments
      - events
      - namespaces
      - nodes
      - persistentvolumeclaims
      - pods
      - pods/exec
      - secrets
      - serviceaccounts
      - services
      - services/finalizers
      - pods
      - subjectaccessreviews
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowbuilds
      - sonataflowbuilds/status
      - sonataflowplatforms
      - sonataflowplatforms/finalizers
      - sonataflowplatforms/status
      - sonataflows
      - sonataflows/finalizers
      - sonataflows/status
      - pods
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - configmaps
      - deployments
      - events
      - namespaces
      - nodes
      - persistentvolumeclaims
      - pods
      - pods/exec
      - secrets
      - serviceaccounts
      - services
      - services/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "*"
    resources:
      - configmaps
      - deployments
      - events
      - namespaces
      - nodes
      - persistentvolumeclaims
      - pods
      - pods/exec
      - secrets
      - serviceaccounts
      - services
      - services/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - tokenreviews
      - subjectaccessreviews
    verbs:
      - create
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
