---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-07-28 - 21:35:37 +0000
  labels:
    app.kubernetes.io/name: my-project
    app.kubernetes.io/version: 0.0.1
  name: my-project
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-project
        app.kubernetes.io/version: 0.0.1
    spec:
      containerConcurrency: 0
      containers:
        - image: quay.io/lmotta/test:0.0.1
          name: my-project
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
