declare LoanApplication
  amount: Integer
  approved: Boolean
  deposit: Integer
  approvedRate: Integer
  lengthYears: Integer
  explanation: String
  insuranceCost: Integer
end

declare Applicant
  age: Integer
  applicationDate: java.util.Date
  creditRating: String
  name: String
  approved: Boolean
end

declare IncomeSource
  amount: Integer
  type: String
end

declare Bankruptcy
  amountOwed: Integer
  yearOfOccurrence: Integer
end