# KIE Sandbox application
extendedServiceUrl: "https://extended-services.{{ .Values.global.openshiftRouteDomain }}"
corsProxyUrl: "https://cors-proxy.{{ .Values.global.openshiftRouteDomain }}"
openshiftRoute:
  enabled: true
  host: kie-sandbox.{{ .Values.global.openshiftRouteDomain }}

# Cors Proxy component
cors_proxy:
  openshiftRoute:
    enabled: true
    host: cors-proxy.{{ .Values.global.openshiftRouteDomain }}

# Extended services component
extended_services:
  openshiftRoute:
    enabled: true
    host: extended-services.{{ .Values.global.openshiftRouteDomain }}

global:
  ingressSource: "openshift"
  openshiftRouteDomain: ocp-example.com