# KIE Sandbox application
kie_sandbox:
  env:
    - name: "KIE_SANDBOX_EXTENDED_SERVICES_URL"
      value: "http://extended-services.{{ .Values.global.clusterDomain }}"
    - name: "KIE_SANDBOX_CORS_PROXY_URL"
      value: "http://cors-proxy.{{ .Values.global.clusterDomain }}"

  ingress:
    enabled: true
    className: "{{ .Values.global.ingressClass }}"
    annotations: {}
    hosts:
      - host: kie-sandbox.{{ .Values.global.clusterDomain }}
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

# Cors Proxy component
cors_proxy:
  ingress:
    enabled: true
    className: "{{ .Values.global.ingressClass }}"
    annotations: {}
    hosts:
      - host: cors-proxy.{{ .Values.global.clusterDomain }}
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

# Extended Services component
extended_services:
  ingress:
    enabled: true
    className: "{{ .Values.global.ingressClass }}"
    annotations: {}
    hosts:
      - host: extended-services.{{ .Values.global.clusterDomain }}
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

global:
  ingressSource: "kubernetes"
  ingressClass: nginx
  clusterDomain: kubernetes.example.com
