
# KIE Sandbox application
extendedServiceUrl: "http://extended-services.local"
corsProxyUrl: "http://cors-proxy.local"
ingress:
  enabled: true
  annotations: {}
  hosts:
    - paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Cors Proxy component
corsProxy:
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

# Extended services component
extendedServices:
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

ingressSource: "openshift"