# Extended services component
# -- The Extended Services application name
name: extended-services

# @ignored
replicaCount: 1

# -- Image source configuration for the Extended Services image
image:
  registry: quay.io
  account: kie-tools
  name: kie-sandbox-extended-services-image
  pullPolicy: IfNotPresent
  tag: "latest"

# -- Pull secrets used when pulling Extended Services image
imagePullSecrets: []

# -- Overrides charts name
nameOverride: ""
# -- Overrides charts full name
fullnameOverride: ""

# -- Extended Services ServiceAccount configuration (https://kubernetes.io/docs/concepts/security/service-accounts/)
serviceAccount:
  create: true
  annotations: {}
  name: ""

# @ignored
podAnnotations: {}

# @ignored
podSecurityContext: {}

# @ignored
securityContext: {}

# -- Extended Services Service configuration (https://kubernetes.io/docs/concepts/services-networking/service/)
service:
  type: ClusterIP
  port: 21345
  nodePort: ""

# -- Extended Services Ingress configuration (https://kubernetes.io/docs/concepts/services-networking/ingress/)
ingress:
  enabled: false
  className: "{{ .Values.global.kubernetesIngressClass }}"
  annotations: {}
  hosts:
    - host: extended-services.{{ .Values.global.kubernetesClusterDomain }}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# -- Extended Services OpenShift Route configuration (https://docs.openshift.com/container-platform/4.14/networking/routes/route-configuration.html)
openshiftRoute:
  enabled: false
  annotations: {}
  host: extended-services.{{ .Values.global.openshiftRouteDomain }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None

# @ignored
resources: {}

# -- Extended Services HorizontalPodAutoscaler configuration (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# @ignored
nodeSelector: {}

# @ignored
tolerations: []

# @ignored
affinity: {}

# @ignored
global:
  openshiftRouteDomain: ocp-example.com
  kubernetesIngressClass: nginx
  kubernetesClusterDomain: k8s-example.com
