export const root = {
  element: "DMN13.xsd__definitions",
  type: "DMN13__tDefinitions",
};

export const ns = new Map<string, string>([
  ["https://www.omg.org/spec/DMN/20191111/MODEL/", ""],
  ["", "https://www.omg.org/spec/DMN/20191111/MODEL/"],
  ["https://www.omg.org/spec/DMN/20191111/DMNDI/", "dmndi:"],
  ["dmndi:", "https://www.omg.org/spec/DMN/20191111/DMNDI/"],
  ["http://www.omg.org/spec/DMN/20180521/DC/", "dc:"],
  ["dc:", "http://www.omg.org/spec/DMN/20180521/DC/"],
  ["http://www.omg.org/spec/DMN/20180521/DI/", "di:"],
  ["di:", "http://www.omg.org/spec/DMN/20180521/DI/"],
]);

// TODO: Import these from parser.ts
export type TypeDef = { type: string; isArray: boolean; isOptional: boolean };
export type Meta = Record<string, Record<string, TypeDef>>;

export const meta = {
  DMN13__tDMNElement: {
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tNamedElement: {
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tDMNElementReference: {
    "@_href": { type: "string", isArray: false, isOptional: false },
  },
  DMN13__tDefinitions: {
    "@_expressionLanguage": { type: "string", isArray: false, isOptional: true },
    "@_typeLanguage": { type: "string", isArray: false, isOptional: true },
    "@_namespace": { type: "string", isArray: false, isOptional: false },
    "@_exporter": { type: "string", isArray: false, isOptional: true },
    "@_exporterVersion": { type: "string", isArray: false, isOptional: true },
    import: { type: "DMN13__tImport", isArray: true, isOptional: true },
    itemDefinition: { type: "DMN13__tItemDefinition", isArray: true, isOptional: true },
    decision: { type: "DMN13__tDecision", isArray: true, isOptional: true },
    businessKnowledgeModel: { type: "DMN13__tBusinessKnowledgeModel", isArray: true, isOptional: true },
    decisionService: { type: "DMN13__tDecisionService", isArray: true, isOptional: true },
    inputData: { type: "DMN13__tInputData", isArray: true, isOptional: true },
    knowledgeSource: { type: "DMN13__tKnowledgeSource", isArray: true, isOptional: true },
    group: { type: "DMN13__tGroup", isArray: true, isOptional: true },
    textAnnotation: { type: "DMN13__tTextAnnotation", isArray: true, isOptional: true },
    association: { type: "DMN13__tAssociation", isArray: true, isOptional: true },
    elementCollection: { type: "DMN13__tElementCollection", isArray: true, isOptional: true },
    performanceIndicator: { type: "DMN13__tPerformanceIndicator", isArray: true, isOptional: true },
    organizationUnit: { type: "DMN13__tOrganizationUnit", isArray: true, isOptional: true },
    "dmndi:DMNDI": { type: "DMNDI13__DMNDI", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tImport: {
    "@_namespace": { type: "string", isArray: false, isOptional: false },
    "@_locationURI": { type: "string", isArray: false, isOptional: true },
    "@_importType": { type: "string", isArray: false, isOptional: false },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tElementCollection: {
    drgElement: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tDRGElement: {
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tDecision: {
    question: { type: "string", isArray: false, isOptional: true },
    allowedAnswers: { type: "string", isArray: false, isOptional: true },
    variable: { type: "DMN13__tInformationItem", isArray: false, isOptional: true },
    informationRequirement: { type: "DMN13__tInformationRequirement", isArray: true, isOptional: true },
    knowledgeRequirement: { type: "DMN13__tKnowledgeRequirement", isArray: true, isOptional: true },
    authorityRequirement: { type: "DMN13__tAuthorityRequirement", isArray: true, isOptional: true },
    supportedObjective: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    impactedPerformanceIndicator: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    decisionMaker: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    decisionOwner: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    usingProcess: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    usingTask: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    literalExpression: { type: "DMN13__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN13__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN13__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN13__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN13__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN13__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN13__tList", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tBusinessContextElement: {
    "@_URI": { type: "string", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tPerformanceIndicator: {
    impactingDecision: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    "@_URI": { type: "string", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tOrganizationUnit: {
    decisionMade: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    decisionOwned: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    "@_URI": { type: "string", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tInvocable: {
    variable: { type: "DMN13__tInformationItem", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tBusinessKnowledgeModel: {
    encapsulatedLogic: { type: "DMN13__tFunctionDefinition", isArray: false, isOptional: true },
    knowledgeRequirement: { type: "DMN13__tKnowledgeRequirement", isArray: true, isOptional: true },
    authorityRequirement: { type: "DMN13__tAuthorityRequirement", isArray: true, isOptional: true },
    variable: { type: "DMN13__tInformationItem", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tInputData: {
    variable: { type: "DMN13__tInformationItem", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tKnowledgeSource: {
    "@_locationURI": { type: "string", isArray: false, isOptional: true },
    authorityRequirement: { type: "DMN13__tAuthorityRequirement", isArray: true, isOptional: true },
    type: { type: "string", isArray: false, isOptional: true },
    owner: { type: "DMN13__tDMNElementReference", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tInformationRequirement: {
    requiredDecision: { type: "DMN13__tDMNElementReference", isArray: false, isOptional: true },
    requiredInput: { type: "DMN13__tDMNElementReference", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tKnowledgeRequirement: {
    requiredKnowledge: { type: "DMN13__tDMNElementReference", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tAuthorityRequirement: {
    requiredDecision: { type: "DMN13__tDMNElementReference", isArray: false, isOptional: true },
    requiredInput: { type: "DMN13__tDMNElementReference", isArray: false, isOptional: true },
    requiredAuthority: { type: "DMN13__tDMNElementReference", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tExpression: {
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tItemDefinition: {
    "@_typeLanguage": { type: "string", isArray: false, isOptional: true },
    "@_isCollection": { type: "boolean", isArray: false, isOptional: true },
    itemComponent: { type: "DMN13__tItemDefinition", isArray: true, isOptional: true },
    functionItem: { type: "DMN13__tFunctionItem", isArray: false, isOptional: true },
    typeRef: { type: "string", isArray: false, isOptional: true },
    allowedValues: { type: "DMN13__tUnaryTests", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tFunctionItem: {
    "@_outputTypeRef": { type: "string", isArray: false, isOptional: true },
    parameters: { type: "DMN13__tInformationItem", isArray: true, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tLiteralExpression: {
    "@_expressionLanguage": { type: "string", isArray: false, isOptional: true },
    text: { type: "string", isArray: false, isOptional: true },
    importedValues: { type: "DMN13__tImportedValues", isArray: false, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tInvocation: {
    literalExpression: { type: "DMN13__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN13__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN13__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN13__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN13__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN13__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN13__tList", isArray: false, isOptional: true },
    binding: { type: "DMN13__tBinding", isArray: true, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tBinding: {
    parameter: { type: "DMN13__tInformationItem", isArray: false, isOptional: false },
    literalExpression: { type: "DMN13__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN13__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN13__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN13__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN13__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN13__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN13__tList", isArray: false, isOptional: true },
  },
  DMN13__tInformationItem: {
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tDecisionTable: {
    "@_hitPolicy": { type: "DMN13__tHitPolicy", isArray: false, isOptional: true },
    "@_aggregation": { type: "DMN13__tBuiltinAggregator", isArray: false, isOptional: true },
    "@_preferredOrientation": { type: "DMN13__tDecisionTableOrientation", isArray: false, isOptional: true },
    "@_outputLabel": { type: "string", isArray: false, isOptional: true },
    input: { type: "DMN13__tInputClause", isArray: true, isOptional: true },
    output: { type: "DMN13__tOutputClause", isArray: true, isOptional: false },
    annotation: { type: "DMN13__tRuleAnnotationClause", isArray: true, isOptional: true },
    rule: { type: "DMN13__tDecisionRule", isArray: true, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tInputClause: {
    inputExpression: { type: "DMN13__tLiteralExpression", isArray: false, isOptional: false },
    inputValues: { type: "DMN13__tUnaryTests", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tOutputClause: {
    "@_name": { type: "string", isArray: false, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    outputValues: { type: "DMN13__tUnaryTests", isArray: false, isOptional: true },
    defaultOutputEntry: { type: "DMN13__tLiteralExpression", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tRuleAnnotationClause: {
    "@_name": { type: "string", isArray: false, isOptional: true },
  },
  DMN13__tDecisionRule: {
    inputEntry: { type: "DMN13__tUnaryTests", isArray: true, isOptional: true },
    outputEntry: { type: "DMN13__tLiteralExpression", isArray: true, isOptional: false },
    annotationEntry: { type: "DMN13__tRuleAnnotation", isArray: true, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tRuleAnnotation: {
    text: { type: "string", isArray: false, isOptional: true },
  },
  DMN13__tImportedValues: {
    "@_expressionLanguage": { type: "string", isArray: false, isOptional: true },
    importedElement: { type: "string", isArray: false, isOptional: false },
    "@_namespace": { type: "string", isArray: false, isOptional: false },
    "@_locationURI": { type: "string", isArray: false, isOptional: true },
    "@_importType": { type: "string", isArray: false, isOptional: false },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tArtifact: {
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tGroup: {
    "@_name": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tTextAnnotation: {
    "@_textFormat": { type: "string", isArray: false, isOptional: true },
    text: { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tAssociation: {
    "@_associationDirection": { type: "DMN13__tAssociationDirection", isArray: false, isOptional: true },
    sourceRef: { type: "DMN13__tDMNElementReference", isArray: false, isOptional: false },
    targetRef: { type: "DMN13__tDMNElementReference", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tContext: {
    contextEntry: { type: "DMN13__tContextEntry", isArray: true, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tContextEntry: {
    variable: { type: "DMN13__tInformationItem", isArray: false, isOptional: true },
    literalExpression: { type: "DMN13__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN13__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN13__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN13__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN13__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN13__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN13__tList", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tFunctionDefinition: {
    "@_kind": { type: "DMN13__tFunctionKind", isArray: false, isOptional: true },
    formalParameter: { type: "DMN13__tInformationItem", isArray: true, isOptional: true },
    literalExpression: { type: "DMN13__tLiteralExpression", isArray: false, isOptional: true },
    invocation: { type: "DMN13__tInvocation", isArray: false, isOptional: true },
    decisionTable: { type: "DMN13__tDecisionTable", isArray: false, isOptional: true },
    context: { type: "DMN13__tContext", isArray: false, isOptional: true },
    functionDefinition: { type: "DMN13__tFunctionDefinition", isArray: false, isOptional: true },
    relation: { type: "DMN13__tRelation", isArray: false, isOptional: true },
    list: { type: "DMN13__tList", isArray: false, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tRelation: {
    column: { type: "DMN13__tInformationItem", isArray: true, isOptional: true },
    row: { type: "DMN13__tList", isArray: true, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tList: {
    literalExpression: { type: "DMN13__tLiteralExpression", isArray: true, isOptional: true },
    invocation: { type: "DMN13__tInvocation", isArray: true, isOptional: true },
    decisionTable: { type: "DMN13__tDecisionTable", isArray: true, isOptional: true },
    context: { type: "DMN13__tContext", isArray: true, isOptional: true },
    functionDefinition: { type: "DMN13__tFunctionDefinition", isArray: true, isOptional: true },
    relation: { type: "DMN13__tRelation", isArray: true, isOptional: true },
    list: { type: "DMN13__tList", isArray: true, isOptional: true },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tUnaryTests: {
    "@_expressionLanguage": { type: "string", isArray: false, isOptional: true },
    text: { type: "string", isArray: false, isOptional: false },
    "@_typeRef": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMN13__tDecisionService: {
    outputDecision: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    encapsulatedDecision: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    inputDecision: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    inputData: { type: "DMN13__tDMNElementReference", isArray: true, isOptional: true },
    variable: { type: "DMN13__tInformationItem", isArray: false, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: false },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "@_label": { type: "string", isArray: false, isOptional: true },
    description: { type: "string", isArray: false, isOptional: true },
    extensionElements: { type: "any", isArray: false, isOptional: true },
  },
  DMNDI13__DMNDI: {
    "dmndi:DMNDiagram": { type: "DMNDI13__DMNDiagram", isArray: true, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: true, isOptional: true },
  },
  DMNDI13__DMNDiagram: {
    "dmndi:Size": { type: "DC__Dimension", isArray: false, isOptional: true },
    "dmndi:DMNShape": { type: "DMNDI13__DMNShape", isArray: true, isOptional: true },
    "dmndi:DMNEdge": { type: "DMNDI13__DMNEdge", isArray: true, isOptional: true },
    "@_name": { type: "string", isArray: false, isOptional: true },
    "@_documentation": { type: "string", isArray: false, isOptional: true },
    "@_resolution": { type: "float", isArray: false, isOptional: true },
    "@_sharedStyle": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: false, isOptional: true },
  },
  DMNDI13__DMNShape: {
    "@_dmnElementRef": { type: "string", isArray: false, isOptional: false },
    "@_isListedInputData": { type: "boolean", isArray: false, isOptional: true },
    "@_isCollapsed": { type: "boolean", isArray: false, isOptional: true },
    "dmndi:DMNLabel": { type: "DMNDI13__DMNLabel", isArray: false, isOptional: true },
    "dmndi:DMNDecisionServiceDividerLine": {
      type: "DMNDI13__DMNDecisionServiceDividerLine",
      isArray: false,
      isOptional: true,
    },
    "dc:Bounds": { type: "DC__Bounds", isArray: false, isOptional: true },
    "@_sharedStyle": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: false, isOptional: true },
  },
  DMNDI13__DMNDecisionServiceDividerLine: {
    "di:waypoint": { type: "DC__Point", isArray: true, isOptional: true },
    "@_sharedStyle": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: false, isOptional: true },
  },
  DMNDI13__DMNEdge: {
    "@_dmnElementRef": { type: "string", isArray: false, isOptional: false },
    "@_sourceElement": { type: "string", isArray: false, isOptional: true },
    "@_targetElement": { type: "string", isArray: false, isOptional: true },
    "dmndi:DMNLabel": { type: "DMNDI13__DMNLabel", isArray: false, isOptional: true },
    "di:waypoint": { type: "DC__Point", isArray: true, isOptional: true },
    "@_sharedStyle": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: false, isOptional: true },
  },
  DMNDI13__DMNLabel: {
    "dmndi:Text": { type: "string", isArray: false, isOptional: true },
    "dc:Bounds": { type: "DC__Bounds", isArray: false, isOptional: true },
    "@_sharedStyle": { type: "string", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
    "dmndi:DMNStyle": { type: "DMNDI13__DMNStyle", isArray: false, isOptional: true },
  },
  DMNDI13__DMNStyle: {
    "@_fontFamily": { type: "string", isArray: false, isOptional: true },
    "@_fontSize": { type: "float", isArray: false, isOptional: true },
    "@_fontItalic": { type: "boolean", isArray: false, isOptional: true },
    "@_fontBold": { type: "boolean", isArray: false, isOptional: true },
    "@_fontUnderline": { type: "boolean", isArray: false, isOptional: true },
    "@_fontStrikeThrough": { type: "boolean", isArray: false, isOptional: true },
    "@_labelHorizontalAlignement": { type: "DC__AlignmentKind", isArray: false, isOptional: true },
    "@_labelVerticalAlignment": { type: "DC__AlignmentKind", isArray: false, isOptional: true },
    "dmndi:FillColor": { type: "DC__Color", isArray: false, isOptional: true },
    "dmndi:StrokeColor": { type: "DC__Color", isArray: false, isOptional: true },
    "dmndi:FontColor": { type: "DC__Color", isArray: false, isOptional: true },
    "@_id": { type: "string", isArray: false, isOptional: true },
    "di:extension": { type: "any", isArray: false, isOptional: true },
  },
  DC__Color: {
    "@_red": { type: "integer", isArray: false, isOptional: false },
    "@_green": { type: "integer", isArray: false, isOptional: false },
    "@_blue": { type: "integer", isArray: false, isOptional: false },
  },
  DC__Point: {
    "@_x": { type: "float", isArray: false, isOptional: false },
    "@_y": { type: "float", isArray: false, isOptional: false },
  },
  DC__Dimension: {
    "@_width": { type: "float", isArray: false, isOptional: false },
    "@_height": { type: "float", isArray: false, isOptional: false },
  },
  DC__Bounds: {
    "@_x": { type: "float", isArray: false, isOptional: false },
    "@_y": { type: "float", isArray: false, isOptional: false },
    "@_width": { type: "float", isArray: false, isOptional: false },
    "@_height": { type: "float", isArray: false, isOptional: false },
  },
};
