---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-manager-role
rules:
  - apiGroups:
      - route.openshift.io
    resources:
      - route
      - routes
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - route/finalizers
      - routes/finalizers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - patch
      - watch
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
      - imagestreamtags
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams/finalizers
      - imagestreamtags/finalizers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - patch
      - watch
  - apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs
      - builds
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs/finalizers
      - builds/finalizers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - patch
      - watch
  - apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs/instantiatebinary
    verbs:
      - create
