kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leases
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
