kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leases-binding
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
roleRef:
  kind: ClusterRole
  name: leases
  apiGroup: rbac.authorization.k8s.io
