# permissions for end users to view sonataflowplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sonataflowplatform-viewer-role
rules:
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowplatforms
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowplatforms/status
    verbs:
      - get
