# permissions for end users to edit sonataflowworkflowbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sonataflowbuild-editor-role
rules:
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowbuilds
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowbuilds/status
    verbs:
      - get
