# permissions for end users to view sonataflowworkflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sonataflowworkflow-viewer-role
rules:
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowworkflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowworkflows/status
    verbs:
      - get
