# permissions for end users to view sonataflowworkflowbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sonataflowbuild-viewer-role
rules:
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowbuilds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowbuilds/status
    verbs:
      - get
