# permissions for end users to edit sonataflowclusterplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sonataflowclusterplatform-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sonataflow-operator
    app.kubernetes.io/part-of: sonataflow-operator
    app.kubernetes.io/managed-by: kustomize
  name: sonataflowclusterplatform-editor-role
rules:
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowclusterplatforms
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflowclusterplatforms/status
    verbs:
      - get
