name: "Setup KIE Tools build environment"
description: ""

inputs:
  os:
    description: "Operating System"
    required: true
  path:
    description: "kie-tools path"
    required: false
    default: "."
  sparse:
    description: "If true, only installs dependencies for affected packages."
    required: false
    default: "false"
  base_sha:
    description: "If `sparse` is true, `base_sha` is used to determine the affected packages."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Print storage usage (before setup)"
      shell: bash
      run: |
        echo "STEP: Print storage usage (before setup)"
        cd ${{ inputs.path }}
        du -sh .

    - name: "Setup pnpm"
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.0.0

    - name: "Setup Node"
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.2

    - name: "Setup JDK 11"
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: "Set up GOLANG 1.17"
      uses: actions/setup-go@v2
      with:
        go-version: "1.17"

    - name: "Setup Yarn"
      shell: bash
      run: |
        echo "STEP: Setup Yarn"
        cd ${{ inputs.path }}
        npm install -g yarn@1.22.10
        pnpm config set network-timeout 1000000

    - name: "Setup default Maven args"
      shell: bash
      run: |
        echo "STEP: Setup default Maven args"
        cd ${{ inputs.path }}
        pnpm -r exec 'bash' '-c' 'mkdir .mvn'
        pnpm -r exec 'bash' '-c' 'echo -B -ntp > .mvn/maven.config'
        pnpm -r exec 'bash' '-c' 'echo -Xmx2g > .mvn/jvm.config'

    - name: "Bootstrap (full)"
      if: inputs.sparse == 'false'
      shell: bash
      run: |
        echo "STEP: Bootstrap (full)"
        cd ${{ inputs.path }}
        pnpm bootstrap

    - name: "Bootstrap (sparse)"
      if: inputs.sparse == 'true'
      shell: bash
      run: |
        echo "STEP: Bootstrap (sparse)"
        cd ${{ inputs.path }}
        pnpm bootstrap -F "...[${{ inputs.base_sha }}]..." -F .

    - name: "Check dependencies mismatches"
      shell: bash
      run: |
        echo "STEP: Check dependencies mismatches"
        cd ${{ inputs.path }}
        npx --yes syncpack@6.2.0 list-mismatches

    - name: "Check format"
      shell: bash
      run: |
        echo "STEP: Check format"
        cd ${{ inputs.path }}
        pnpm format:check

    - name: "Start Xvfb (Ubuntu only)"
      shell: bash
      run: |
        echo "STEP: Start Xvfb (Ubuntu only)"
        cd ${{ inputs.path }}
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
            /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        fi

    - name: "Configure Pagefile (Windows only)"
      if: inputs.os == 'windows-latest'
      uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 16GB
        maximum-size: 16GB
        disk-root: "C:"

    - name: "Increase inotify watches (Ubuntu only)"
      shell: bash
      run: |
        echo "STEP: Increase inotify watches (Ubuntu only)"
        cd ${{ inputs.path }}
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        fi

    - name: "Setup GOLANG packages (Linux)"
      shell: bash
      run: |
        echo "STEP: Setup GOLANG packages (Linux)"
        cd ${{ inputs.path }}
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
          sudo apt update && \
          sudo apt install -y \
          build-essential \
          libgtk-3-dev \
          libappindicator3-dev \
          gir1.2-appindicator3-0.1
        fi

    - name: "Print storage usage (after setup)"
      shell: bash
      run: |
        echo "STEP: Print storage usage (after setup)"
        cd ${{ inputs.path }}
        du -sh .
