name: "Setup Kogito Tooling build environment"
description: "setup"

inputs:
  os:
    description: "Operating System"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Fetch Git tags"
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: "Setup Node"
      uses: actions/setup-node@v1
      with:
        node-version: 16.2.0

    - name: "Setup Yarn and Lerna"
      run: |
        npm install -g lerna@4.0.0 yarn@1.22.10
        yarn config set network-timeout 1000000

    - name: "Bootstrap"
      run: |
        yarn bootstrap

    - name: "Check yarn.lock"
      shell: bash
      run: |
        git diff yarn.lock;
        [ "0" == "$(git diff yarn.lock | wc -l)" ]

    - name: "Check format"
      run: |
        yarn format:check

    - name: "Start Xvfb (Ubuntu only)"
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: "Increase inotify watches (Ubuntu only)"
      run: |
        echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
