name: "Setup Kogito Tooling build environment"
description: "setup"

inputs:
  os:
    description: "Operating System"
    required: true
  path:
    description: "kogito-tooling path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Fetch Git tags"
      shell: bash
      run: |
        cd ${{ inputs.path }}
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        cd -

    - name: "Setup Yarn and Lerna"
      shell: bash
      run: |
        npm install -g lerna@4.0.0 yarn@1.22.10
        yarn config set network-timeout 1000000

    - name: "Bootstrap"
      shell: bash
      run: |
        cd ${{ inputs.path }}
        yarn bootstrap
        cd -

    - name: "Check yarn.lock"
      shell: bash
      run: |
        cd ${{ inputs.path }}
        git diff yarn.lock;
        [ "0" == "$(git diff yarn.lock | wc -l)" ]
        cd -

    - name: "Check format"
      shell: bash
      run: |
        cd ${{ inputs.path }}
        yarn format:check
        cd -

    - name: "Start Xvfb (Ubuntu only)"
      shell: bash
      run: |
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
            /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        fi

    - name: "Increase inotify watches (Ubuntu only)"
      shell: bash
      run: |
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        fi
