package kogito

const NAME = "Kogito"
const SERVER_STATUS = "DMN Runner Status"
const SERVER_STATUS_ON = SERVER_STATUS + ": ON"
const SERVER_STATUS_OFF = SERVER_STATUS + ": OFF"
const START = "Start"
const STARTING = "Starting..."
const STOP = "Stop"
const STOPPING = "Stopping..."
const RESTART = "Restart"
const QUIT = "Quit"
const NOT_STARTED = "Not Started"
const BUSINESS_MODELER = "Open Business Modeler"
const MODELER_LINK = "https://kiegroup.github.io/kogito-online-staging/dmn-runner/#/"
const INFORMATION = "DMN Runner Information"
const INFORMATION_PORT = "Port"
const INFORMATION_RUNNER_PORT = "Runner Port"
const INFORMATION_BUSINESS_MODELER_URL = "Business Modeler URL"
