name: "Setup KIE Tools Bot on Git"
description: ""

runs:
  using: "composite"
  steps:
    - name: "Setup kie-tools-bot"
      shell: bash
      run: |
        echo "STEP: Setup kie-tools-bot"
        git config --global user.email "kietoolsbot@gmail.com"
        git config --global user.name "KIE Tools Bot (kiegroup)"
