#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

resources:
  - manager.yaml
generatorOptions:
  disableNameSuffixHash: true
# No need to generate this CM since we are not using it.
# Must also uncomment config/manager/kustomization.yaml to mount it in the controller

#- files:
#  - controller_manager_config.yaml
#  name: manager-config
configMapGenerator:
  - files:
      - Dockerfile=SonataFlow-Builder.containerfile
    literals:
      - DEFAULT_WORKFLOW_EXTENSION=.sw.json
    name: builder-config
  - files:
      - controllers_cfg.yaml
    name: controllers-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: controller
    newName: docker.io/apache/incubator-kie-sonataflow-operator
    newTag: main
# Patching the manager deployment file to add an env var with the operator namespace in
patchesJson6902:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
    target:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: system
      version: v1
