/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.kie.workbench.common.services.backend.social
import org.ext.uberfire.social.activities.model.SocialActivitiesEvent;

global org.kie.workbench.common.services.backend.social.SocialTimelineRulesQuery queryAPI;
global java.util.List socialEvents;
global java.lang.String filter;
rule "filterTimelineRecentAssets"
when
  $result:SocialActivitiesEvent(getLinkTarget() contains filter) from queryAPI.getTypeCached("RESOURCE_ADDED_EVENT",
                                                                                             "RESOURCE_UPDATE_EVENT",
                                                                                             "NEW_REPOSITORY_EVENT",
                                                                                             "NEW_ORGANIZATIONAL_UNIT",
                                                                                             "ORGANIZATIONAL_UNIT_UPDATED",
                                                                                             "REPO_ADDED_TO_ORGANIZATIONAL_UNIT",
                                                                                             "REPO_REMOVED_FROM_ORGANIZATIONAL_UNIT",
                                                                                             "NEW_PROJECT",
                                                                                             "COMMENT_ADDED")
  eval( true )
then
  socialEvents.add($result);
end