apiVersion: v2
name: incubator-kie-runtime-tools-consoles-helm-chart
description: A Helm chart to deploy Runtime Tools Consoles on Kubernetes
type: application
version: 2.2.999
appVersion: 2.2.999
dependencies:
  - name: management-console
    version: 2.2.999
    condition: management-console.enabled
