package org.kie.uberfire.social.activities.drools
import org.kie.uberfire.social.activities.model.SocialActivitiesEvent;

global org.kie.uberfire.social.activities.drools.SocialTimelineRulesQuery queryAPI;
global java.util.List socialEvents;
global java.util.List socialEvents;
global java.lang.String filter;
rule "filterTimelineRecentAssets"
when
  $result:SocialActivitiesEvent(getLinkTarget() contains filter) from queryAPI.getTypeCached("RESOURCE_ADDED_EVENT", "RESOURCE_UPDATE_EVENT")
  eval( true )
then
  socialEvents.add($result);
end