package org.kie.uberfire.social.activities.drools
import org.kie.uberfire.social.activities.model.SocialActivitiesEvent;

global org.kie.uberfire.social.activities.drools.SocialTimelineRulesQuery queryAPI;
global java.util.List socialEvents;
rule "Get N Type Cached"
when
  $result:SocialActivitiesEvent() from queryAPI.getNEventsFromEachType(10,"FOLLOW_USER", "NEW_REPOSITORY_EVENT")
  eval( true )
then
  socialEvents.add($result);
end