package org.kie.uberfire.social.activities.drools
import org.kie.uberfire.social.activities.model.SocialActivitiesEvent;

global org.kie.uberfire.social.activities.drools.SocialTimelineRulesQuery queryAPI;
global java.util.List socialEvents;
global java.util.List socialEvents;
global java.lang.String filter;
global java.lang.Integer maxResults;
rule "Get N Type Cached"
when
  $result:SocialActivitiesEvent(getAdicionalInfos() contains filter) from queryAPI.getNEventsFromEachType(maxResults,"RESOURCE_ADDED_EVENT", "RESOURCE_UPDATE_EVENT")
  eval( true )
then
  socialEvents.add($result);
end