package org.kie.uberfire.social.activities.drools
import org.kie.uberfire.social.activities.model.SocialActivitiesEvent;

global org.kie.uberfire.social.activities.drools.SocialTimelineRulesQuery queryAPI;
global java.util.List socialEvents;
rule "Get Type Cached"
when
  $result:SocialActivitiesEvent() from queryAPI.getTypeCached("FOLLOW_USER")
  eval( false )
then
  socialEvents.add($result);
end