/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.drools.guvnor.client.rpc;

import com.google.gwt.user.client.rpc.AsyncCallback;

public interface CategoryServiceAsync {
    
    /** PLACE THE FOLLOWING IN CategoryServiceAsync.java **/

    /** Generated by AsyncInterfaceGenerator hackery */
    public void loadChildCategories(java.lang.String p0, AsyncCallback<java.lang.String[]> cb);
    public void loadRuleListForCategories(org.drools.guvnor.client.rpc.CategoryPageRequest p0, AsyncCallback<org.drools.guvnor.client.rpc.PageResponse<org.drools.guvnor.client.rpc.CategoryPageRow>> cb);
    public void loadRuleListForCategories(java.lang.String p0, int p1, int p2, java.lang.String p3, AsyncCallback<org.drools.guvnor.client.rpc.TableDataResult> cb);
    public void createCategory(java.lang.String p0, java.lang.String p1, java.lang.String p2, AsyncCallback<java.lang.Boolean> cb);
    public void removeCategory(java.lang.String p0, AsyncCallback cb);
    public void renameCategory(java.lang.String p0, java.lang.String p1, AsyncCallback cb);

}
