# The default size of Kaniko PVC when using the internal operator builder manager
defaultPvcKanikoSize: 1Gi
# How much time (in seconds) to wait for a devmode workflow to start.
# This information is used for the controller manager to create new devmode containers and setup the healthcheck probes.
healthFailureThresholdDevMode: 50
# Default image used internally by the Operator Managed Kaniko builder to create the warmup pods
kanikoDefaultWarmerImageTag: gcr.io/kaniko-project/warmer:v1.9.0
# Default image used internally by the Operator Managed Kaniko builder to create the executor pods
kanikoExecutorImageTag: gcr.io/kaniko-project/executor:v1.9.0
# The Jobs Service image to use, if empty the operator will use the default Apache Community one based on the current operator's version
jobsServicePostgreSQLImageTag: ""
jobsServiceEphemeralImageTag: ""
# The Data Index image to use, if empty the operator will use the default Apache Community one based on the current operator's version
dataIndexPostgreSQLImageTag: ""
dataIndexEphemeralTag: ""
# SonataFlow base builder image used in the internal Dockerfile to build workflow applications in preview profile
# Order of precedence is:
# 1. SonataFlowPlatform in the given namespace
# 2. This configuration
# 3. The FROM in the Dockerfile in the operator's namespace "sonataflow-operator-builder-config" configMap.
# If 1 or 2, the FROM tag will be replaced by the tag se there.
# If empty the operator will use the default Apache Community one based on the current operator's version.
sonataFlowBaseBuilderImageTag: ""
# The image to use to deploy SonataFlow workflow images in devmode profile.
# If empty the operator will use the default Apache Community one based on the current operator's version.
sonataFlowDevModeImageTag: ""
# The default name of the builder configMap in the operator's namespace
builderConfigMapName: "sonataflow-operator-builder-config"
