#!/bin/bash -e

function set_infinispan_props() {
    local infinispan_props=""

    if [[ "${INFINISPAN_USEAUTH}" == "true" &&  -z "${INFINISPAN_USERNAME}" ]]; then
        echo "[ERROR] Flag INFINISPAN_USEAUTH set to true, but no username informed. Please use INFINISPAN_USERNAME and INFINISPAN_PASSWORD variables to set the right credentials."
        exit 1
    fi

    if [ -z "${INFINISPAN_USERNAME}" ]; then
        if [ ! -z "${INFINISPAN_USEAUTH}" ]; then
            INFINISPAN_USEAUTH="false"
        fi
    fi
 
    if [ ! -z "${INFINISPAN_USERNAME}" ]; then infinispan_props=$(echo "${infinispan_props} -Dinfinispan_username=${INFINISPAN_USERNAME}"); INFINISPAN_USEAUTH="true"; fi
    if [ ! -z "${INFINISPAN_PASSWORD}" ]; then infinispan_props=$(echo "${infinispan_props} -Dinfinispan_password=${INFINISPAN_PASSWORD}"); fi
    if [ ! -z "${INFINISPAN_USEAUTH}" ]; then infinispan_props=$(echo "${infinispan_props} -Dinfinispan_useauth=${INFINISPAN_USEAUTH}"); fi
    if [ ! -z "${INFINISPAN_AUTHREALM}" ]; then infinispan_props=$(echo "${infinispan_props} -Dinfinispan_authrealm=${INFINISPAN_AUTHREALM}"); fi
    if [ ! -z "${INFINISPAN_SASLMECHANISM}" ]; then infinispan_props=$(echo "${infinispan_props} -Dinfinispan_saslmechanism=${INFINISPAN_SASLMECHANISM}"); fi

    echo $infinispan_props
}

function start() {
    local infinispan_props=$(set_infinispan_props)

    java -Djava.library.path=$KOGITO_HOME/lib \
        -Dquarkus.http.host=0.0.0.0 \
        ${infinispan_props} \
        ${JAVA_OPTS} \
        -jar $KOGITO_HOME/bin/*-runner.jar
}

if [ -z "${TEST}" ]; then
    start
fi