#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: "CI :: Build - Full"

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
    types: [opened, reopened, ready_for_review, synchronize]

env:
  TMPDIR: "/tmp"
  BUILD_ENV__accessErrorsLogFileAbsolutePath: "/tmp/build-env-access-errors.log"
  KOGITO_RUNTIME_version: "111-SNAPSHOT"
  MAVEN_ARGS: "-B -s ${{ github.workspace }}/.github/supporting-files/ci/midstream-mvn-config/settings.xml"
  MAVEN_REPO_TOKEN: ${{ github.token }}

permissions:
  contents: read
  packages: read

jobs:
  run:
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Support longpaths"
        if: runner.os == 'Windows'
        run: git config --system core.longpaths true

      - name: "Checkout"
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v6
        with:
          version: 10.34.4

      - name: "Setup Node"
        uses: actions/setup-node@v6
        with:
          node-version: 24.18.0

      - name: "Setup CI patterns"
        id: ci_patterns
        uses: ./.github/actions/setup-ci-patterns

      - name: "Setup environment"
        if: steps.setup_build_mode.outputs.mode != 'none'
        uses: ./.github/actions/setup-env

      - name: "Setup kie-tools"
        uses: ./.github/actions/setup-kie-tools
        with:
          KOGITO_VERSION: ${{ env.KOGITO_RUNTIME_version }}
          DEPS_BRANCHNAME: ${{ github.head_ref || 'main' }}
          PNPM_FILTER: ""

      - name: Modify pom.xml of sonataflow-quarkus-devui
        run: python .github/supporting-files/ci/osl/pom-manipulation/inject-fmp-executions.py

      - name: "FULL → Build:Prod with all tests & images"
        shell: bash
        env:
          WEBPACK__minimize: "false"
          WEBPACK__tsLoaderTranspileOnly: "false"
          KIE_TOOLS_BUILD__runLinters: "true"
          KIE_TOOLS_BUILD__runTests: "true"
          KIE_TOOLS_BUILD__runEndToEndTests: "true"
          KIE_TOOLS_BUILD__containerizedEndToEndTests: "true"
          KIE_TOOLS_BUILD__buildContainerImages: "true"
          KIE_TOOLS_BUILD__buildExamples: "true"
          KIE_TOOLS_BUILD__ignoreTestFailures: ${{ !github.event.pull_request }}
          KIE_TOOLS_BUILD__ignoreEndToEndTestFailures: ${{ !github.event.pull_request }}
          PLAYWRIGHT_BASE__enableChromiumProject: "true"
          PLAYWRIGHT_BASE__enableGoogleChromeProject: "true"
          PLAYWRIGHT_BASE__enableWebkitProject: "true"
          PLAYWRIGHT_BASE__projectTimeout: "90000"
          PLAYWRIGHT_BASE__expectTimeout: "30000"
          PLAYWRIGHT_BASE__retries: "3"
          PLAYWRIGHT_BASE__workers: "2"
          DISPLAY: ":99.0"
          START_SERVER_AND_TEST_INSECURE: "true"
          NODE_OPTIONS: "--max_old_space_size=6144"
          MAVEN_OPTS: "-Xmx2g"
        run: >-
          eval "pnpm -r --workspace-concurrency=1 build:prod"

      - name: "Check tests result (`main` only)"
        if: always() && !cancelled() && steps.setup_build_mode.outputs.mode != 'none'
        uses: actions/github-script@v9
        env:
          KIE_TOOLS_CI__JUNIT_REPORT_RESULTS_PATTERNS: |-
            ${{ steps.ci_patterns.outputs.tests_reports_patterns }}
            ${{ steps.ci_patterns.outputs.end_to_end_tests_reports_patterns }}
        with:
          result-encoding: string
          script: |
            const patterns = process.env["KIE_TOOLS_CI__JUNIT_REPORT_RESULTS_PATTERNS"]
                                .split("\n")
                                .map(p => p.trim())
                                .filter(p => p);

            const script = require("./scripts/check-junit-report-results/src/index.js");
            await script({ core, glob, patterns });

      - name: "Check build-env access errors log"
        if: always() && !cancelled() && steps.setup_build_mode.outputs.mode != 'none'
        shell: bash
        run: |
          touch "$BUILD_ENV__accessErrorsLogFileAbsolutePath"
          cat "$BUILD_ENV__accessErrorsLogFileAbsolutePath"
          [ "0" == "$(cat "$BUILD_ENV__accessErrorsLogFileAbsolutePath" | wc -l | tr -d ' ')" ]

      - name: "Upload reports and artifacts"
        if: always() && !cancelled() && steps.setup_build_mode.outputs.mode != 'none'
        uses: ./.github/actions/upload-ci-reports-and-artifacts
        with:
          partition_index: ${{ matrix.partition }}

      - name: "Print storage usage (after build)"
        if: always() && !cancelled()
        shell: bash
        run: |
          df -h .
