name: "Kubesmarts :: Daily dev :: Publish"

on:
  schedule:
    - cron: "0 4 * * *" # 4am UTC everyday
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build_and_publish:
    uses: ./.github/workflows/kubesmarts_build_and_publish.yml
    with:
      dry_run: false
      environment: dev
    secrets:
      KIE1_TOKEN: ${{ secrets.KIE1_TOKEN }}
      KIE1_EMAIL: ${{ secrets.KIE1_EMAIL }}
      KIE1_USER_NAME: ${{ secrets.KIE1_USER_NAME }}
