name: "CI :: OSL :: Sync Upstream"

on:
  workflow_dispatch: # Allows you to run the workflow manually from the Actions tab
    inputs:
      dry_run:
        description: "True to perform a dry run (dry run git push and skip create PR step)"
        required: false
        default: "false"

  schedule:
    - cron: "0 2 * * 1" # Runs every Monday at 2 AM UTC (adjust as needed)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Setup git environment
        shell: bash
        run: |
          set -x
          git config --global user.name "${{ secrets.KIE1_USER_NAME }}"
          git config --global user.email "${{ secrets.KIE1_EMAIL }}"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: upstream

      - name: Add Upstream Remote
        run: |
          set -x
          git remote add upstream "${{ vars.UPSTREAM_URL }}"
          git fetch upstream main

      - name: Sync with Upstream Main
        run: |
          set -x
          git merge upstream/main
          git push origin upstream ${{ github.event.inputs.dry_run == 'true' && ' --dry-run' || '' }}
