name: "CI :: OSL :: Publish Images Snapshots"
on:
  workflow_call:
    inputs:
      dry_run:
        type: boolean
        required: true
      USE_REMOTE_ARTIFACTS:
        description: "True to use productized artifacts from Red Hat Maven repository"
        type: boolean
        required: false
        default: false
      KOGITO_VERSION:
        description: "Specify the version for Kogito Runtime"
        type: string
        required: false
        default: "111-SNAPSHOT"
      IMAGE_TAG:
        description: "Specify the tag for the images"
        type: string
        required: false
        default: "main"
      build_operator_bundle:
        description: "Flag to build operator bundle."
        type: boolean
        required: false
        default: true
      build_operator_catalog:
        description: "Flag to build operator catalog."
        type: boolean
        required: false
        default: true

permissions:
  contents: read

jobs:
  publish_images_snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: "Print workflow inputs"
        run: |
          echo "dry_run: ${{ inputs.dry_run }}"
          echo "USE_REMOTE_ARTIFACTS: ${{ inputs.USE_REMOTE_ARTIFACTS }}"
          echo "KOGITO_VERSION: ${{ inputs.KOGITO_VERSION }}"
          echo "IMAGE_TAG: ${{ inputs.IMAGE_TAG }}"

      - name: "Checkout @ GitHub default"
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.IMAGE_TAG }}

      - name: "Exporting KOGITO_RUNTIME_version"
        run: |
          if [ -n "${{ inputs.KOGITO_VERSION }}" ]; then
            echo "KOGITO_RUNTIME_version=${{ inputs.KOGITO_VERSION }}" >> $GITHUB_ENV
          else
            echo "No KOGITO_VERSION input provided. Keeping the default or existing behavior."
          fi

      - name: "Exporting OSL_IMAGE_TAG"
        run: |
          if [ -n "${{ inputs.IMAGE_TAG }}" ]; then
            echo "OSL_IMAGE_TAG=${{ inputs.IMAGE_TAG }}" >> $GITHUB_ENV
          elif [ -n "${{ inputs.KOGITO_VERSION }}" ]; then
            echo "OSL_IMAGE_TAG=${{ inputs.KOGITO_VERSION }}" >> $GITHUB_ENV
          else
            echo "OSL_IMAGE_TAG=main" >> $GITHUB_ENV
          fi

      - name: "Verify Exported Variables"
        run: |
          echo "KOGITO_RUNTIME_version: $KOGITO_RUNTIME_version"
          echo "OSL_IMAGE_TAG: $OSL_IMAGE_TAG"

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Setup kie-tools repository"
        uses: ./.github/actions/setup-kie-tools
        with:
          KOGITO_VERSION: ${{ inputs.KOGITO_VERSION }}
          DEPS_BRANCHNAME: ${{ inputs.IMAGE_TAG }}
          PNPM_FILTER: ${{ vars.IMAGES_UPSTREAM_PNPM_FILTER }}
          USE_REMOTE_ARTIFACTS: ${{ inputs.USE_REMOTE_ARTIFACTS }}

      - name: "Build Images"
        shell: bash
        env:
          DROOLS_AND_KOGITO__skip: true
          KOGITO_RUNTIME_version: "${{ inputs.KOGITO_VERSION }}"
          SONATAFLOW_DEVMODE_IMAGE__sonataflowQuarkusDevUiVersion: "${{ inputs.KOGITO_VERSION }}"
          KIE_TOOLS_BUILD__buildContainerImages: "true"
          KIE_TOOLS_BUILD__runEndToEndTests: "false"
          KIE_TOOLS_BUILD__runTests: "false"
          # TODO: on upstream implement a root-env named defaultRegistry and defaultAccount and change on every image package
          SONATAFLOW_BUILDER_IMAGE__registry: "quay.io"
          SONATAFLOW_BUILDER_IMAGE__account: "kubesmarts"
          SONATAFLOW_DEVMODE_IMAGE__registry: "quay.io"
          SONATAFLOW_DEVMODE_IMAGE__account: "kubesmarts"
          SONATAFLOW_MANAGEMENT_CONSOLE__registry: "quay.io"
          SONATAFLOW_MANAGEMENT_CONSOLE__account: "kubesmarts"
          KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__registry: "quay.io"
          KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__account: "kubesmarts"
          KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__registry: "quay.io"
          KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__account: "kubesmarts"
          KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__registry: "quay.io"
          KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__account: "kubesmarts"
          KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__registry: "quay.io"
          KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__account: "kubesmarts"
          SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageRegistry: "quay.io"
          SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageAccount: "kubesmarts"
          SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageRegistry: "quay.io"
          SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageAccount: "kubesmarts"
          SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageRegistry: "quay.io"
          SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageAccount: "kubesmarts"
          SONATAFLOW_OPERATOR__registry: "quay.io"
          SONATAFLOW_OPERATOR__account: "kubesmarts"
          KOGITO_DB_MIGRATOR_TOOL_IMAGE__registry: "quay.io"
          KOGITO_DB_MIGRATOR_TOOL_IMAGE__account: "kubesmarts"
        run: |
          eval "pnpm ${{ vars.IMAGES_UPSTREAM_PNPM_FILTER }} --workspace-concurrency=1 build:prod"
          eval "pnpm -F @kie-tools/sonataflow-operator... --workspace-concurrency=1 image:bundle:build"

      - name: "Login to Quay"
        uses: docker/login-action@v4
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_ACCOUNT }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: "Push Images to Quay"
        if: ${{ !inputs.dry_run }}
        run: |
          for image in ${{ vars.PUBLISH_IMAGES_LIST }}; do
            echo "Pushing $image to Quay"

            if [ "${{ env.OSL_IMAGE_TAG }}" = "main" ]; then
              echo "OSL_IMAGE_TAG is 'main'. Pushing main tag."
              docker push quay.io/kubesmarts/$image:main || { echo "Failed to push $image:main"; exit 1; }
            else
              echo "OSL_IMAGE_TAG is not 'main'. Tagging and pushing snapshot."
              docker tag quay.io/kubesmarts/$image:main quay.io/kubesmarts/$image:${{ env.OSL_IMAGE_TAG }}
              docker push quay.io/kubesmarts/$image:${{ env.OSL_IMAGE_TAG }} || { echo "Failed to push $image with tag $OSL_IMAGE_TAG to Quay"; exit 1; }
            fi
          done

      - name: "Push operator bundle to Quay"
        if: ${{ !inputs.dry_run }}
        run: |
          echo "Pushing operator bundle to Quay"

          if [ "${{ env.OSL_IMAGE_TAG }}" = "main" ]; then
            echo "OSL_IMAGE_TAG is 'main'. Pushing main tag."
            docker push quay.io/kubesmarts/logic-rhel9-operator-bundle:main || { echo "Failed to push logic-rhel9-operator-bundle:main"; exit 1; }
          else
            echo "OSL_IMAGE_TAG is not 'main'. Tagging and pushing snapshot."
            docker tag quay.io/kubesmarts/logic-rhel9-operator-bundle:main quay.io/kubesmarts/logic-rhel9-operator-bundle:${{ env.OSL_IMAGE_TAG }}
            docker push quay.io/kubesmarts/logic-rhel9-operator-bundle:${{ env.OSL_IMAGE_TAG }} || { echo "Failed to push logic-rhel9-operator-bundle with tag $OSL_IMAGE_TAG to Quay"; exit 1; }
          fi

      - name: "Build operator catalog"
        shell: bash
        env:
          DROOLS_AND_KOGITO__skip: true
          KOGITO_RUNTIME_version: "${{ inputs.KOGITO_VERSION }}"
          SONATAFLOW_DEVMODE_IMAGE__sonataflowQuarkusDevUiVersion: "${{ inputs.KOGITO_VERSION }}"
          KIE_TOOLS_BUILD__buildContainerImages: "true"
          KIE_TOOLS_BUILD__runEndToEndTests: "false"
          KIE_TOOLS_BUILD__runTests: "false"
          SONATAFLOW_BUILDER_IMAGE__registry: "quay.io"
          SONATAFLOW_BUILDER_IMAGE__account: "kubesmarts"
          SONATAFLOW_DEVMODE_IMAGE__registry: "quay.io"
          SONATAFLOW_DEVMODE_IMAGE__account: "kubesmarts"
          SONATAFLOW_MANAGEMENT_CONSOLE__registry: "quay.io"
          SONATAFLOW_MANAGEMENT_CONSOLE__account: "kubesmarts"
          KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__registry: "quay.io"
          KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__account: "kubesmarts"
          KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__registry: "quay.io"
          KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__account: "kubesmarts"
          KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__registry: "quay.io"
          KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__account: "kubesmarts"
          KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__registry: "quay.io"
          KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__account: "kubesmarts"
          SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageRegistry: "quay.io"
          SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageAccount: "kubesmarts"
          SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageRegistry: "quay.io"
          SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageAccount: "kubesmarts"
          SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageRegistry: "quay.io"
          SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageAccount: "kubesmarts"
          SONATAFLOW_OPERATOR__registry: "quay.io"
          SONATAFLOW_OPERATOR__account: "kubesmarts"
          KOGITO_DB_MIGRATOR_TOOL_IMAGE__registry: "quay.io"
          KOGITO_DB_MIGRATOR_TOOL_IMAGE__account: "kubesmarts"
          IMAGE_TAG: ${{ env.OSL_IMAGE_TAG }}
        run: |
          eval "pnpm -F @kie-tools/sonataflow-operator... --workspace-concurrency=1 image:catalog:build"

      - name: "Push operator catalog to Quay"
        if: ${{ !inputs.dry_run }}
        run: |
          echo "Pushing operator catalog to Quay"

          echo "Pushing logic-rhel9-operator-catalog:${{ env.OSL_IMAGE_TAG }}"
          docker push quay.io/kubesmarts/logic-rhel9-operator-catalog:${{ env.OSL_IMAGE_TAG }} || { echo "Failed to push logic-rhel9-operator-catalog with tag $OSL_IMAGE_TAG to Quay"; exit 1; }
