name: "CI :: OSL :: Publish Images Snapshots Weekly"
on:
  schedule:
    - cron: "0 10 * * 5"

permissions:
  contents: read

jobs:
  call-images-publishing-workflow:
    uses: ./.github/workflows/osl_publish_images_snapshots.yml
    with:
      dry_run: false
      USE_REMOTE_ARTIFACTS: false
      KOGITO_VERSION: "111-SNAPSHOT"
      IMAGE_TAG: "main"
    secrets: inherit
