#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: "Publish emscripten-fs"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
  pull_request:
    paths:
      - ".github/supporting-files/publish_emscripten_fs"
      - ".github/workflows/publish_emscripten_fs.yml"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout kie-tools"
        uses: actions/checkout@v3

      - name: "Build and publish"
        working-directory: ./.github/supporting-files/publish_emscripten_fs
        env:
          NPM_TOKEN: ${{ secrets.KIEGROUP_NPM_TOKEN }}
        run: |
          npm version ${{ github.event.inputs.version }}
          ./build.sh
          export ACTUAL=$(node ./test.js)
          export EXPECTED='emscripten FS is alive!'
          if [ "$ACTUAL" == "$EXPECTED" ]; then
            echo "Test passed."
            if [ ${{ github.event.pull_request }} ]; then
              echo "CI. Publish skipped."
            else
              echo "Publishing."
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              npm publish --access public
            fi
          else
            echo "Test failed:"
            echo "Actual: '$ACTUAL'"
            echo "Expected: '$EXPECTED'"
            false
          fi
