name: "Staging :: Dry Run"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # 3am UTC everyday
  pull_request:
    branches: ["**"]
    paths:
      - ".github/workflows/staging*"
      - ".github/actions/**"

concurrency:
  group: ${{ github.event.pull_request && format('staging-dry-run-pr-{0}', github.event.pull_request.number) || format('staging-dry-run-ref-{0}', github.ref_name) }}
  cancel-in-progress: true

jobs:
  dry_run:
    uses: ./.github/workflows/staging_build.yml
    with:
      dry_run: true
      base_ref: ${{ github.event.pull_request && github.base_ref || github.ref }}
