name: "CI :: Verify update version"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      TARGET_VERSION: "1.0.0"
      DEFAULT_VERSION: "0.0.0"
    steps:
      - name: "Checkout kie-tools"
        uses: actions/checkout@v3

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Bootstrap"
        uses: ./.github/actions/bootstrap

      - name: "Update version to 1.0.0"
        shell: bash
        run: |
          pnpm update-version-to ${{ env.TARGET_VERSION }}

      - name: "Verify version to 1.0.0"
        shell: bash
        run: |
          pnpm verify-version-to ${{ env.TARGET_VERSION }}

      - name: "Update version to 0.0.0"
        shell: bash
        run: |
          pnpm update-version-to ${{ env.DEFAULT_VERSION }}

      - name: "Check hanging uncommitted files (you should commit those!)"
        shell: bash
        run: |
          git diff
          [ "0" == "$(git diff | wc -l | tr -d ' ')" ]
